#!/usr/bin/env python3
"""promote.py -- Lane 1 write adapter, engine-independent half (Frontal_Mem M2).

Turns an owner-confirmed triage manifest (from `consolidate.py confirm`) into normalized,
attributed Lane 1 post records, and emits a ready-to-run DotTalk++ script of `BBS POST`
commands. The actual DBF write is performed by running that script through the shell's
attributed path (`current_member()` + `post_new`, AIF-075) -- a maintainer/host step, because
the engine cannot run in the sandbox.

This is the seam the thesis and the design call for: the judgment (consolidate.py) and the
rendering (here) are engine-free and fully testable; only the final `post_new` touches the
store. The same records feed a future C++ `PSEUDO PROMOTE` without change.

Attribution and safety (AIF-075):
  * Posts are written by `BBS POST`, which attributes to the logged-in member -- NEVER author 0.
    The script header refuses to run anonymous (anon POST is denied by RBAC anyway).
  * `BBS POST <board> SUBJECT <subject> BODY <text>` -- body reads to end of line, so it MUST be
    comment-free (no `&&`) and single-line; the subject must not contain the literal ` BODY `.
  * The source-lane marker (session / pseudochat / ollama-chat) rides in the subject prefix
    until the store grows a first-class post `kind` field (design note, future work).

References: DESIGN_bbs_pseudochat_two_lanes.md (normalize-on-collect, hybrid), thesis 5.5
(contradiction is flagged, never silently resolved), src/cli/cmd_bbs.cpp (the grammar).
"""

import argparse
import datetime as dt
import json
import re
import sys
from pathlib import Path

DEFAULT_BOARD = "board.afb.chat"     # existing topic board (design default), + source-lane marker
BODY_KEYWORD = " BODY "              # the shell marker that splits subject from body


def sanitize_line(text):
    """One ASCII line, comment-free, whitespace-collapsed. Compression is forgetting: a promoted
    post is an atomic canonical claim, not a transcript."""
    if text is None:
        text = ""
    text = str(text).replace("&&", "and")          # never let the DotTalk++ comment marker in
    text = text.encode("ascii", "replace").decode("ascii")
    text = " ".join(text.split())                  # collapse all whitespace / newlines
    return text.strip()


def make_subject(item):
    lane = (item.get("provenance", {}) or {}).get("source_lane") or "session"
    marker = "[consolidated:%s]" % lane
    summary = sanitize_line(item.get("summary") or item.get("id") or "memory")
    subject = "%s %s" % (marker, summary)
    subject = subject.replace(BODY_KEYWORD, " body ")   # must not collide with the split marker
    return subject[:160]                                # keep subjects bounded


def make_body(item):
    parts = [sanitize_line(item.get("summary"))]
    if item.get("needs_reconsolidation"):
        parts.append("[reconsolidate vs %s]" % sanitize_line(item.get("contradicts")))
    for link in item.get("links", []) or []:
        t = sanitize_line(link.get("type")); to = sanitize_line(link.get("to"))
        if t and to:
            parts.append("[%s -> %s]" % (t, to))
    prov = item.get("provenance", {}) or {}
    parts.append("(provenance: session=%s agent=%s date=%s score=%s)" % (
        sanitize_line(prov.get("session")), sanitize_line(prov.get("agent")),
        sanitize_line(prov.get("date")), item.get("score")))
    return sanitize_line(" ".join(p for p in parts if p))


def render(manifest, board=DEFAULT_BOARD):
    posts = []
    for item in manifest.get("to_write", []):
        if not item.get("owner_confirmed"):
            continue                                    # defence in depth: only confirmed writes
        subject = make_subject(item)
        body = make_body(item)
        posts.append({
            "board": board,
            "subject": subject,
            "body": body,
            "command": "BBS POST %s SUBJECT %s BODY %s" % (board, subject, body),
            "author": "current_member (attributed at run time; never author 0)",
            "source_lane": (item.get("provenance", {}) or {}).get("source_lane") or "session",
            "from_candidate": item.get("id"),
        })
    return {
        "schema": "frontal-mem-lane1-posts-v1",
        "generated_at_utc": dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "board": board,
        "session": manifest.get("session", {}),
        "count": len(posts),
        "posts": posts,
    }


def to_script(rendered):
    """A DotTalk++ .dts script. Comment lines use && on their OWN lines; POST lines carry no
    comment (BBS POST body reads to end of line)."""
    lines = [
        "&& Frontal_Mem Lane 1 write adapter -- generated by tools/memory/promote.py",
        "&& Run as a logged-in member (NOT anon; anon POST is denied by RBAC / AIF-075).",
        "&& Each line writes one attributed, normalized post to the durable board.",
        "&& generated_at_utc: " + rendered["generated_at_utc"],
    ]
    for p in rendered["posts"]:
        lines.append(p["command"])
    return "\n".join(lines) + "\n"


def _load(path):
    return json.loads(Path(path).read_text(encoding="utf-8"))


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="cmd", required=True)
    r = sub.add_parser("render", help="confirmed manifest -> attributed post records + .dts script")
    r.add_argument("--manifest", required=True)
    r.add_argument("--board", default=DEFAULT_BOARD)
    r.add_argument("--out-json", default=None)
    r.add_argument("--out-script", default=None)
    args = ap.parse_args(argv)

    if args.cmd == "render":
        rendered = render(_load(args.manifest), board=args.board)
        script = to_script(rendered)
        if args.out_json:
            Path(args.out_json).write_text(json.dumps(rendered, indent=2) + "\n", encoding="utf-8")
        if args.out_script:
            Path(args.out_script).write_text(script, encoding="utf-8")
        if not args.out_json and not args.out_script:
            print(script)
        print("rendered %d attributed post(s) for %s" % (rendered["count"], rendered["board"]),
              file=sys.stderr)
        return 0
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
