"""Generated GUI text seed. Do not edit by hand."""

from __future__ import annotations

SUPPORTED_LOCALES = ('en-US', 'es', 'fr', 'de', 'it')

TEXT: dict[str, dict[str, str]] = {
    'gui.app.title': {
        'en-US': 'DotTalk++ Workbench',
        'es': 'DotTalk++ Workbench',
        'fr': 'DotTalk++ Workbench',
        'de': 'DotTalk++ Workbench',
        'it': 'DotTalk++ Workbench',
    },
    'gui.status.ready': {
        'en-US': 'Ready',
        'es': 'Listo',
        'fr': 'Pret',
        'de': 'Bereit',
        'it': 'Pronto',
    },
    'gui.area.none_open': {
        'en-US': 'No open areas',
        'es': 'No hay areas abiertas',
        'fr': 'Aucune zone ouverte',
        'de': 'Keine offenen Bereiche',
        'it': 'Nessuna area aperta',
    },
    'gui.table.none_open': {
        'en-US': 'No table is open',
        'es': 'No hay tabla abierta',
        'fr': 'Aucune table ouverte',
        'de': 'Keine Tabelle geoeffnet',
        'it': 'Nessuna tabella aperta',
    },
    'gui.area.none_selected': {
        'en-US': 'No area is selected',
        'es': 'No hay area seleccionada',
        'fr': 'Aucune zone selectionnee',
        'de': 'Kein Bereich ausgewaehlt',
        'it': 'Nessuna area selezionata',
    },
    'gui.action.open_table': {
        'en-US': 'Open Table',
        'es': 'Abrir tabla',
        'fr': 'Ouvrir table',
        'de': 'Tabelle oeffnen',
        'it': 'Apri tabella',
    },
    'gui.action.open_workspace': {
        'en-US': 'Open Workspace',
        'es': 'Abrir espacio de trabajo',
        'fr': 'Ouvrir espace de travail',
        'de': 'Arbeitsbereich oeffnen',
        'it': 'Apri workspace',
    },
    'gui.action.save_workspace': {
        'en-US': 'Save Workspace',
        'es': 'Guardar espacio de trabajo',
        'fr': 'Enregistrer espace de travail',
        'de': 'Arbeitsbereich speichern',
        'it': 'Salva workspace',
    },
    'gui.action.save_workspace_as': {
        'en-US': 'Save Workspace As',
        'es': 'Guardar espacio de trabajo como',
        'fr': 'Enregistrer espace de travail sous',
        'de': 'Arbeitsbereich speichern unter',
        'it': 'Salva workspace con nome',
    },
    'gui.label.workspace_graph': {
        'en-US': 'Workspace Graph',
        'es': 'Grafo de espacio de trabajo',
        'fr': 'Graphe espace de travail',
        'de': 'Arbeitsbereichsgraph',
        'it': 'Grafo workspace',
    },
    'gui.action.refresh': {
        'en-US': 'Refresh',
        'es': 'Actualizar',
        'fr': 'Actualiser',
        'de': 'Aktualisieren',
        'it': 'Aggiorna',
    },
    'gui.action.refresh_snapshot': {
        'en-US': 'Refresh Snapshot',
        'es': 'Actualizar vista',
        'fr': "Actualiser l'instantane",
        'de': 'Snapshot aktualisieren',
        'it': 'Aggiorna snapshot',
    },
    'gui.action.close_area': {
        'en-US': 'Close Area',
        'es': 'Cerrar area',
        'fr': 'Fermer zone',
        'de': 'Bereich schliessen',
        'it': 'Chiudi area',
    },
    'gui.label.command': {
        'en-US': 'Command',
        'es': 'Comando',
        'fr': 'Commande',
        'de': 'Befehl',
        'it': 'Comando',
    },
    'gui.action.run': {
        'en-US': 'Run',
        'es': 'Ejecutar',
        'fr': 'Executer',
        'de': 'Ausfuehren',
        'it': 'Esegui',
    },
    'gui.label.areas': {
        'en-US': 'Workspace Areas',
        'es': 'Areas de trabajo',
        'fr': 'Zones de travail',
        'de': 'Arbeitsbereiche',
        'it': 'Aree di lavoro',
    },
    'gui.tab.browse': {
        'en-US': 'Browse',
        'es': 'Explorar',
        'fr': 'Parcourir',
        'de': 'Durchsuchen',
        'it': 'Sfoglia',
    },
    'gui.tab.structure': {
        'en-US': 'Structure',
        'es': 'Estructura',
        'fr': 'Structure',
        'de': 'Struktur',
        'it': 'Struttura',
    },
    'gui.menu.file': {
        'en-US': 'File',
        'es': 'Archivo',
        'fr': 'Fichier',
        'de': 'Datei',
        'it': 'File',
    },
    'gui.menu.workspace': {
        'en-US': 'Workspace',
        'es': 'Espacio de trabajo',
        'fr': 'Espace de travail',
        'de': 'Arbeitsbereich',
        'it': 'Workspace',
    },
    'gui.menu.area': {
        'en-US': 'Area',
        'es': 'Area',
        'fr': 'Zone',
        'de': 'Bereich',
        'it': 'Area',
    },
    'gui.menu.language': {
        'en-US': 'Language',
        'es': 'Idioma',
        'fr': 'Langue',
        'de': 'Sprache',
        'it': 'Lingua',
    },
    'gui.menu.help': {
        'en-US': 'Help',
        'es': 'Ayuda',
        'fr': 'Aide',
        'de': 'Hilfe',
        'it': 'Aiuto',
    },
    'gui.action.exit': {
        'en-US': 'Exit',
        'es': 'Salir',
        'fr': 'Quitter',
        'de': 'Beenden',
        'it': 'Esci',
    },
    'gui.action.about': {
        'en-US': 'About',
        'es': 'Acerca de',
        'fr': 'A propos',
        'de': 'Info',
        'it': 'Informazioni',
    },
    'gui.about.title': {
        'en-US': 'About DotTalk++ Workbench',
        'es': 'Acerca de DotTalk++ Workbench',
        'fr': 'A propos de DotTalk++ Workbench',
        'de': 'Info zu DotTalk++ Workbench',
        'it': 'Informazioni su DotTalk++ Workbench',
    },
    'gui.about.body': {
        'en-US': 'DotTalk++ Workbench opens workspaces with areas tables indexes relations browsers and command lanes.',
        'es': 'DotTalk++ Workbench abre espacios de trabajo con areas tablas indices relaciones navegadores y comandos.',
        'fr': 'DotTalk++ Workbench ouvre des espaces de travail avec zones tables index relations navigateurs et commandes.',
        'de': 'DotTalk++ Workbench oeffnet Arbeitsbereiche mit Bereichen Tabellen Indizes Relationen Browsern und Befehlen.',
        'it': 'DotTalk++ Workbench apre workspace con aree tabelle indici relazioni browser e comandi.',
    },
    'gui.locale.en_us': {
        'en-US': 'English',
        'es': 'Ingles',
        'fr': 'Anglais',
        'de': 'Englisch',
        'it': 'Inglese',
    },
    'gui.locale.es': {
        'en-US': 'Spanish',
        'es': 'Espanol',
        'fr': 'Espagnol',
        'de': 'Spanisch',
        'it': 'Spagnolo',
    },
    'gui.locale.fr': {
        'en-US': 'French',
        'es': 'Frances',
        'fr': 'Francais',
        'de': 'Franzoesisch',
        'it': 'Francese',
    },
    'gui.locale.de': {
        'en-US': 'German',
        'es': 'Aleman',
        'fr': 'Allemand',
        'de': 'Deutsch',
        'it': 'Tedesco',
    },
    'gui.locale.it': {
        'en-US': 'Italian',
        'es': 'Italiano',
        'fr': 'Italien',
        'de': 'Italienisch',
        'it': 'Italiano',
    },
    'gui.status.opening_table': {
        'en-US': 'Opening table...',
        'es': 'Abriendo tabla...',
        'fr': 'Ouverture de la table...',
        'de': 'Tabelle wird geoeffnet...',
        'it': 'Apertura tabella...',
    },
    'gui.status.refreshing_snapshot': {
        'en-US': 'Refreshing snapshot...',
        'es': 'Actualizando vista...',
        'fr': "Actualisation de l'instantane...",
        'de': 'Snapshot wird aktualisiert...',
        'it': 'Aggiornamento snapshot...',
    },
    'gui.status.closing_area': {
        'en-US': 'Closing area...',
        'es': 'Cerrando area...',
        'fr': 'Fermeture de la zone...',
        'de': 'Bereich wird geschlossen...',
        'it': 'Chiusura area...',
    },
    'gui.status.selecting_area': {
        'en-US': 'Selecting area...',
        'es': 'Seleccionando area...',
        'fr': 'Selection de la zone...',
        'de': 'Bereich wird ausgewaehlt...',
        'it': 'Selezione area...',
    },
    'gui.status.running_command': {
        'en-US': 'Running command...',
        'es': 'Ejecutando comando...',
        'fr': 'Execution de la commande...',
        'de': 'Befehl wird ausgefuehrt...',
        'it': 'Esecuzione comando...',
    },
    'gui.status.rows_shown_of': {
        'en-US': 'rows shown of',
        'es': 'filas mostradas de',
        'fr': 'lignes affichees sur',
        'de': 'Zeilen angezeigt von',
        'it': 'righe mostrate di',
    },
    'gui.severity.info': {
        'en-US': 'info',
        'es': 'info',
        'fr': 'info',
        'de': 'info',
        'it': 'info',
    },
    'gui.severity.warning': {
        'en-US': 'warning',
        'es': 'advertencia',
        'fr': 'avertissement',
        'de': 'warnung',
        'it': 'avviso',
    },
    'gui.severity.error': {
        'en-US': 'error',
        'es': 'error',
        'fr': 'erreur',
        'de': 'fehler',
        'it': 'errore',
    },
    'gui.task.queued': {
        'en-US': 'Queued',
        'es': 'En cola',
        'fr': 'En file',
        'de': 'In Warteschlange',
        'it': 'In coda',
    },
    'gui.task.cancelled_before_start': {
        'en-US': 'Cancelled before start',
        'es': 'Cancelado antes de iniciar',
        'fr': 'Annule avant demarrage',
        'de': 'Vor dem Start abgebrochen',
        'it': "Annullato prima dell'avvio",
    },
    'gui.task.opening_table': {
        'en-US': 'Opening table',
        'es': 'Abriendo tabla',
        'fr': 'Ouverture de la table',
        'de': 'Tabelle wird geoeffnet',
        'it': 'Apertura tabella',
    },
    'gui.task.open_table_finished': {
        'en-US': 'Open table finished',
        'es': 'Apertura de tabla terminada',
        'fr': 'Ouverture de table terminee',
        'de': 'Tabelle oeffnen abgeschlossen',
        'it': 'Apertura tabella completata',
    },
    'gui.task.table_opened': {
        'en-US': 'Table opened',
        'es': 'Tabla abierta',
        'fr': 'Table ouverte',
        'de': 'Tabelle geoeffnet',
        'it': 'Tabella aperta',
    },
    'gui.task.open_table_failed': {
        'en-US': 'Open table failed',
        'es': 'No se pudo abrir la tabla',
        'fr': 'Echec ouverture table',
        'de': 'Tabelle oeffnen fehlgeschlagen',
        'it': 'Apertura tabella non riuscita',
    },
    'gui.task.selecting_area': {
        'en-US': 'Selecting work area',
        'es': 'Seleccionando area de trabajo',
        'fr': 'Selection zone de travail',
        'de': 'Arbeitsbereich wird ausgewaehlt',
        'it': 'Selezione area di lavoro',
    },
    'gui.task.area_selected': {
        'en-US': 'Work area selected',
        'es': 'Area de trabajo seleccionada',
        'fr': 'Zone de travail selectionnee',
        'de': 'Arbeitsbereich ausgewaehlt',
        'it': 'Area di lavoro selezionata',
    },
    'gui.task.select_area_failed': {
        'en-US': 'Select work area failed',
        'es': 'No se pudo seleccionar el area',
        'fr': 'Echec selection zone',
        'de': 'Arbeitsbereich auswaehlen fehlgeschlagen',
        'it': 'Selezione area non riuscita',
    },
    'gui.task.closing_area': {
        'en-US': 'Closing work area',
        'es': 'Cerrando area de trabajo',
        'fr': 'Fermeture zone de travail',
        'de': 'Arbeitsbereich wird geschlossen',
        'it': 'Chiusura area di lavoro',
    },
    'gui.task.area_closed': {
        'en-US': 'Work area closed',
        'es': 'Area de trabajo cerrada',
        'fr': 'Zone de travail fermee',
        'de': 'Arbeitsbereich geschlossen',
        'it': 'Area di lavoro chiusa',
    },
    'gui.task.close_area_failed': {
        'en-US': 'Close work area failed',
        'es': 'No se pudo cerrar el area',
        'fr': 'Echec fermeture zone',
        'de': 'Arbeitsbereich schliessen fehlgeschlagen',
        'it': 'Chiusura area non riuscita',
    },
    'gui.task.areas_listed': {
        'en-US': 'Work areas listed',
        'es': 'Areas de trabajo listadas',
        'fr': 'Zones de travail listees',
        'de': 'Arbeitsbereiche aufgelistet',
        'it': 'Aree di lavoro elencate',
    },
    'gui.task.running_command': {
        'en-US': 'Running command',
        'es': 'Ejecutando comando',
        'fr': 'Execution commande',
        'de': 'Befehl wird ausgefuehrt',
        'it': 'Esecuzione comando',
    },
    'gui.task.command_finished': {
        'en-US': 'Command finished',
        'es': 'Comando terminado',
        'fr': 'Commande terminee',
        'de': 'Befehl abgeschlossen',
        'it': 'Comando completato',
    },
    'gui.task.command_completed': {
        'en-US': 'Command completed',
        'es': 'Comando completado',
        'fr': 'Commande executee',
        'de': 'Befehl erledigt',
        'it': 'Comando eseguito',
    },
    'gui.task.command_failed': {
        'en-US': 'Command failed',
        'es': 'Comando fallido',
        'fr': 'Echec commande',
        'de': 'Befehl fehlgeschlagen',
        'it': 'Comando non riuscito',
    },
    'gui.task.building_snapshot': {
        'en-US': 'Building table snapshot',
        'es': 'Creando vista de tabla',
        'fr': 'Creation instantane table',
        'de': 'Tabellen-Snapshot wird erstellt',
        'it': 'Creazione snapshot tabella',
    },
    'gui.task.snapshot_ready': {
        'en-US': 'Table snapshot ready',
        'es': 'Vista de tabla lista',
        'fr': 'Instantane table pret',
        'de': 'Tabellen-Snapshot bereit',
        'it': 'Snapshot tabella pronto',
    },
    'gui.task.snapshot_failed': {
        'en-US': 'Table snapshot failed',
        'es': 'Vista de tabla fallida',
        'fr': 'Echec instantane table',
        'de': 'Tabellen-Snapshot fehlgeschlagen',
        'it': 'Snapshot tabella non riuscito',
    },
    'gui.open_table.path_missing': {
        'en-US': 'No table path was provided.',
        'es': 'No se proporciono una ruta de tabla.',
        'fr': 'Aucun chemin de table fourni.',
        'de': 'Kein Tabellenpfad angegeben.',
        'it': 'Nessun percorso tabella fornito.',
    },
    'gui.open_table.opened': {
        'en-US': 'Table opened in a new GUI work area.',
        'es': 'Tabla abierta en una nueva area de trabajo GUI.',
        'fr': 'Table ouverte dans une nouvelle zone GUI.',
        'de': 'Tabelle in neuem GUI-Arbeitsbereich geoeffnet.',
        'it': 'Tabella aperta in una nuova area GUI.',
    },
    'gui.open_table.failed': {
        'en-US': 'Unable to open table.',
        'es': 'No se pudo abrir la tabla.',
        'fr': "Impossible d'ouvrir la table.",
        'de': 'Tabelle konnte nicht geoeffnet werden.',
        'it': 'Impossibile aprire la tabella.',
    },
    'gui.area.not_open': {
        'en-US': 'Requested GUI work area is not open.',
        'es': 'El area de trabajo GUI solicitada no esta abierta.',
        'fr': "La zone GUI demandee n'est pas ouverte.",
        'de': 'Der angeforderte GUI-Arbeitsbereich ist nicht geoeffnet.',
        'it': "L'area GUI richiesta non e aperta.",
    },
    'gui.area.selected': {
        'en-US': 'GUI work area selected.',
        'es': 'Area de trabajo GUI seleccionada.',
        'fr': 'Zone GUI selectionnee.',
        'de': 'GUI-Arbeitsbereich ausgewaehlt.',
        'it': 'Area GUI selezionata.',
    },
    'gui.area.closed': {
        'en-US': 'GUI work area closed.',
        'es': 'Area de trabajo GUI cerrada.',
        'fr': 'Zone GUI fermee.',
        'de': 'GUI-Arbeitsbereich geschlossen.',
        'it': 'Area GUI chiusa.',
    },
    'gui.command.empty': {
        'en-US': 'No command text was provided.',
        'es': 'No se proporciono texto de comando.',
        'fr': 'Aucun texte de commande fourni.',
        'de': 'Kein Befehlstext angegeben.',
        'it': 'Nessun testo comando fornito.',
    },
    'gui.command.skeleton': {
        'en-US': 'Command dispatch skeleton only.',
        'es': 'Solo esqueleto de despacho de comando.',
        'fr': 'Squelette de dispatch commande seulement.',
        'de': 'Nur Befehlsverteilungs-Skelett.',
        'it': 'Solo scheletro di dispatch comando.',
    },
    'gui.snapshot.no_current_table': {
        'en-US': 'No current table is selected.',
        'es': 'No hay tabla actual seleccionada.',
        'fr': 'Aucune table courante selectionnee.',
        'de': 'Keine aktuelle Tabelle ausgewaehlt.',
        'it': 'Nessuna tabella corrente selezionata.',
    },
    'gui.snapshot.first_record_past_end': {
        'en-US': 'Requested first record is past the end of the table.',
        'es': 'El primer registro solicitado esta despues del final de la tabla.',
        'fr': 'Le premier enregistrement demande depasse la fin de la table.',
        'de': 'Der angeforderte erste Datensatz liegt hinter dem Tabellenende.',
        'it': 'Il primo record richiesto supera la fine della tabella.',
    },
    'gui.snapshot.record_read_failed': {
        'en-US': 'Stopped snapshot because a record could not be read.',
        'es': 'Vista detenida porque no se pudo leer un registro.',
        'fr': "Instantane arrete car un enregistrement n'a pas pu etre lu.",
        'de': 'Snapshot gestoppt, weil ein Datensatz nicht gelesen werden konnte.',
        'it': 'Snapshot interrotto perche un record non poteva essere letto.',
    },
    'gui.snapshot.failed': {
        'en-US': 'Unable to build table snapshot.',
        'es': 'No se pudo crear la vista de tabla.',
        'fr': "Impossible de creer l'instantane de table.",
        'de': 'Tabellen-Snapshot konnte nicht erstellt werden.',
        'it': 'Impossibile creare lo snapshot tabella.',
    },
}
