#include "gui/core/gui_command_catalog.hpp"

namespace dottalk::gui {

const std::vector<GuiCommandAction>& gui_command_catalog() {
    static const std::vector<GuiCommandAction> catalog {
        {"Work", "Workspace Summary", "WORKSPACE", GuiCommandActionKind::run, {}},
        {"Work", "Open DBF Workspace", "WORKSPACE OPEN DBF", GuiCommandActionKind::run, {}},
        {"Work", "Open Workspace From Folder", "WORKSPACE OPEN ", GuiCommandActionKind::prefill, {}},
        {"Work", "Save Workspace", "WORKSPACE SAVE ", GuiCommandActionKind::prefill, {}},
        {"Work", "Load Workspace", "WORKSPACE LOAD ", GuiCommandActionKind::prefill, {}},
        {"Work", "Close Workspace", "WORKSPACE CLOSE", GuiCommandActionKind::run, {}},
        {"Work", "Current Area", "AREA", GuiCommandActionKind::run, {}},
        {"Work", "All DbAreas", "DBAREAS", GuiCommandActionKind::run, {}},
        {"Work", "Workspace Report", "WSREPORT", GuiCommandActionKind::run, {}},

        {"Table", "Structure", "STRUCT", GuiCommandActionKind::run, {}},
        {"Table", "Fields", "FIELDS", GuiCommandActionKind::run, {}},
        {"Table", "Table Status", "STATUS", GuiCommandActionKind::run, {}},
        {"Table", "Metadata", "TABLEMETA", GuiCommandActionKind::run, {}},
        {"Table", "Validate", "VALIDATE", GuiCommandActionKind::run, {}},
        {"Table", "DDL", "DDL ", GuiCommandActionKind::prefill, {}},
        {"Table", "Show Internal State", "SHOW", GuiCommandActionKind::run, {}},
        {"Table", "Buffering On", "TABLE ON", GuiCommandActionKind::run, {}},
        {"Table", "Buffering Off", "TABLE OFF", GuiCommandActionKind::run, {}},
        {"Table", "Show Stale Fields", "TABLE STALE", GuiCommandActionKind::run, {}},
        {"Table", "Apply / Fresh", "TABLE FRESH ", GuiCommandActionKind::prefill, {}},
        {"Table", "Commit Changes", "COMMIT", GuiCommandActionKind::run, {}},

        {"Record", "Record View", "RECORDVIEW", GuiCommandActionKind::run, {}},
        {"Record", "Display Current", "DISPLAY", GuiCommandActionKind::run, {}},
        {"Record", "Current Record Context", "RECORD", GuiCommandActionKind::run, {}},
        {"Record", "Go To Record", "GOTO ", GuiCommandActionKind::prefill, {}},
        {"Record", "Top", "TOP", GuiCommandActionKind::run, {}},
        {"Record", "Bottom", "BOTTOM", GuiCommandActionKind::run, {}},
        {"Record", "Skip Forward", "SKIP 1", GuiCommandActionKind::run, {}},
        {"Record", "Skip Back", "SKIP -1", GuiCommandActionKind::run, {}},
        {"Record", "Append", "APPEND", GuiCommandActionKind::run, {}},
        {"Record", "Append Blank", "APPEND_BLANK", GuiCommandActionKind::run, {}},
        {"Record", "Edit", "EDIT", GuiCommandActionKind::run, {}},
        {"Record", "Replace Field", "REPLACE ", GuiCommandActionKind::prefill, {}},
        {"Record", "Delete", "DELETE", GuiCommandActionKind::run, {}},
        {"Record", "Recall", "RECALL", GuiCommandActionKind::run, {}},
        {"Record", "Pack", "PACK", GuiCommandActionKind::run, {}},
        {"Record", "Zap All Records", "", GuiCommandActionKind::info, "ZAP is destructive. Type ZAP manually when intentional."},
        {"Record", "Lock Record", "LOCK", GuiCommandActionKind::run, {}},
        {"Record", "Unlock", "UNLOCK", GuiCommandActionKind::run, {}},

        {"Index", "Set Index Container", "SET INDEX TO ", GuiCommandActionKind::prefill, {}},
        {"Index", "Set Order / Tag", "SET ORDER TO ", GuiCommandActionKind::prefill, {}},
        {"Index", "Physical Order", "SET ORDER TO 0", GuiCommandActionKind::run, {}},
        {"Index", "Seek Key", "SEEK ", GuiCommandActionKind::prefill, {}},
        {"Index", "Find Key", "FIND ", GuiCommandActionKind::prefill, {}},
        {"Index", "IndexSeek", "INDEXSEEK ", GuiCommandActionKind::prefill, {}},
        {"Index", "Ascending", "ASCEND", GuiCommandActionKind::run, {}},
        {"Index", "Descending", "DESCEND", GuiCommandActionKind::run, {}},
        {"Index", "Reindex", "REINDEX", GuiCommandActionKind::run, {}},
        {"Index", "Build LMDB-CDX", "BUILDLMDB", GuiCommandActionKind::run, {}},
        {"Index", "CNX Container", "CNX ", GuiCommandActionKind::prefill, {}},
        {"Index", "CDX Diagnostics", "CDX ", GuiCommandActionKind::prefill, {}},
        {"Index", "LMDB Diagnostics", "LMDB ", GuiCommandActionKind::prefill, {}},

        {"Lists", "List Records", "LIST", GuiCommandActionKind::run, {}},
        {"Lists", "List First 10", "LIST 10", GuiCommandActionKind::run, {}},
        {"Lists", "SmartList", "SMARTLIST", GuiCommandActionKind::run, {}},
        {"Lists", "SmartList FOR", "SMARTLIST 20 FOR ", GuiCommandActionKind::prefill, {}},
        {"Lists", "Display Current", "DISPLAY", GuiCommandActionKind::run, {}},
        {"Lists", "Count", "COUNT FOR ", GuiCommandActionKind::prefill, {}},
        {"Lists", "Sum", "SUM ", GuiCommandActionKind::prefill, {}},
        {"Lists", "Average", "AVERAGE ", GuiCommandActionKind::prefill, {}},
        {"Lists", "WHERE / SQL-like Filter", "WHERE ", GuiCommandActionKind::prefill, {}},
        {"Lists", "Set Filter", "SET FILTER TO ", GuiCommandActionKind::prefill, {}},
        {"Lists", "Clear Filter", "SET FILTER TO", GuiCommandActionKind::run, {}},
        {"Lists", "Predicate Help", "PREDHELP", GuiCommandActionKind::run, {}},
        {"Lists", "Predicate Catalog", "PREDICATES", GuiCommandActionKind::run, {}},

        {"Browse", "Browse Current Table", "BROWSE", GuiCommandActionKind::run, {}},
        {"Browse", "Simple Browser", "SIMPLEBROWSER ", GuiCommandActionKind::prefill, {}},
        {"Browse", "Smart Browser", "SMARTBROWSER ", GuiCommandActionKind::prefill, {}},
        {"Browse", "Developer Browser", "BROWSER", GuiCommandActionKind::run, {}},
        {"Browse", "Record View", "RECORDVIEW", GuiCommandActionKind::run, {}},
        {"Browse", "Related Children", "SIMPLEBROWSER SHOW CHILDREN LIMIT 20", GuiCommandActionKind::prefill, {}},
        {"Browse", "Browse FOR", "SIMPLEBROWSER FOR ", GuiCommandActionKind::prefill, {}},
        {"Browse", "Browse ORDER", "SIMPLEBROWSER ORDER ", GuiCommandActionKind::prefill, {}},
        {"Browse", "ERSATZ Browser", "ERSATZ", GuiCommandActionKind::run, {}},
        {"Browse", "ERSATZ Load", "ERSATZ LOAD", GuiCommandActionKind::run, {}},
        {"Browse", "ERSATZ Demo Script", "DOTSCRIPT ersatz_browser", GuiCommandActionKind::run, {}},
        {"Browse", "Relation Result Browser", "REL ENUM LIMIT 10", GuiCommandActionKind::run, {}},
        {"Browse", "Relation List Browser", "REL LIST ALL", GuiCommandActionKind::run, {}},

        {"Rel", "Set Relation", "SET RELATION TO ", GuiCommandActionKind::prefill, {}},
        {"Rel", "Set Relation Additive", "SET RELATION ADDITIVE TO ", GuiCommandActionKind::prefill, {}},
        {"Rel", "Relation Off Into", "SET RELATION OFF INTO ", GuiCommandActionKind::prefill, {}},
        {"Rel", "Clear Current Relations", "SET RELATION OFF ALL", GuiCommandActionKind::run, {}},
        {"Rel", "Relation List", "REL LIST", GuiCommandActionKind::run, {}},
        {"Rel", "Relation List All", "REL LIST ALL", GuiCommandActionKind::run, {}},
        {"Rel", "Relation Refresh", "REL REFRESH", GuiCommandActionKind::run, {}},
        {"Rel", "Add Native Relation", "REL ADD ", GuiCommandActionKind::prefill, {}},
        {"Rel", "Clear Native Relation", "REL CLEAR ", GuiCommandActionKind::prefill, {}},
        {"Rel", "Save Relations", "REL SAVE ", GuiCommandActionKind::prefill, {}},
        {"Rel", "Load Relations", "REL LOAD ", GuiCommandActionKind::prefill, {}},
        {"Rel", "Enumerate Relation Path", "REL ENUM LIMIT 10 ", GuiCommandActionKind::prefill, {}},

        {"Tuple", "Tuple All Fields", "TUPLE *", GuiCommandActionKind::run, {}},
        {"Tuple", "Tuple Fields", "TUPLE ", GuiCommandActionKind::prefill, {}},
        {"Tuple", "Tuple From Area", "TUPLE #", GuiCommandActionKind::prefill, {}},
        {"Tuple", "Mixed-Area Tuple", "TUPLE #9.*,#11.LNAME", GuiCommandActionKind::prefill, {}},
        {"Tuple", "TupTalk", "TUPTALK ", GuiCommandActionKind::prefill, {}},
        {"Tuple", "Tuple Export", "TUPEXPORT ", GuiCommandActionKind::prefill, {}},
        {"Tuple", "Tuple Validate", "TUPVALIDATE", GuiCommandActionKind::run, {}},

        {"Cmd", "Help", "HELP", GuiCommandActionKind::run, {}},
        {"Cmd", "Fox Help", "FOXHELP", GuiCommandActionKind::run, {}},
        {"Cmd", "Command Catalog", "CMDHELP", GuiCommandActionKind::run, {}},
        {"Cmd", "Validate Command Catalog", "CMDHELPCHK", GuiCommandActionKind::run, {}},
        {"Cmd", "Argument Parser Check", "CMDARGCHK", GuiCommandActionKind::run, {}},
        {"Cmd", "Run DotScript", "DOTSCRIPT ", GuiCommandActionKind::prefill, {}},
        {"Cmd", "Test Harness", "TEST ", GuiCommandActionKind::prefill, {}},
        {"Cmd", "Set Variable", "SET VAR ", GuiCommandActionKind::prefill, {}},
        {"Cmd", "Force Set Variable", "SET VAR! ", GuiCommandActionKind::prefill, {}},
        {"Cmd", "SQL Version", "SQLVER", GuiCommandActionKind::run, {}},
        {"Cmd", "Version", "VERSION", GuiCommandActionKind::run, {}},
        {"Cmd", "GPS", "GPS", GuiCommandActionKind::run, {}},
        {"Cmd", "SQLite Status", "SQLITE", GuiCommandActionKind::run, {}},
        {"Cmd", "SQL Execute", "SQL ", GuiCommandActionKind::prefill, {}},
        {"Cmd", "SQL Select", "SQLSEL ", GuiCommandActionKind::prefill, {}},
    };

    return catalog;
}

} // namespace dottalk::gui
