#!/usr/bin/env python3
from __future__ import annotations

import argparse
import csv
import datetime as dt
import hashlib
import json
from pathlib import Path
from typing import Any, Dict, List


EXPECTED_DD092_STATUS = "DDICT_HELP_CMDHELPCHK_INTEGRATION_PLAN_READY"

SURFACES = [
    ("DDICT HELP", "Show DDICT command syntax and notes."),
    ("DDICT STATUS", "Show active Data Dictionary catalog status."),
    ("DDICT TABLES", "List active Data Dictionary catalog tables and artifact presence."),
    ("DDICT OBJECTS [TYPE <type>] [PROFILE <profile>]", "List Data Dictionary objects with optional filters."),
    ("DDICT FIELDS <table>", "List catalog field objects for a table."),
    ("DDICT TAGS <table>", "List catalog tag/index definitions for a table."),
    ("DDICT REL <object-id-or-name> [IN|OUT|BOTH]", "List catalog relationship edges for an object."),
    ("DDICT EVIDENCE <object-id-or-name>", "Show bounded evidence and attribute-evidence rows for an object."),
]

PROTECTED_ARTIFACTS = [
    "dottalkpp/data/help",
    "dottalkpp/data/help/help_topic.dbf",
    "dottalkpp/data/help/commands.dbf",
    "src/cli/cmd_ddict.cpp",
    "src/cli/shell_commands.cpp",
    "src/cli/command_registry.cpp",
]


def utc_now() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat(timespec="seconds")


def read_json(path: Path) -> Dict[str, Any]:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8", errors="replace"))
    except Exception as exc:
        return {"_read_error": str(exc)}


def write_json(path: Path, obj: Dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(obj, indent=2, sort_keys=True) + "\n", encoding="utf-8")


def write_csv(path: Path, rows: List[Dict[str, Any]], fields: List[str]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as f:
        w = csv.DictWriter(f, fieldnames=fields, lineterminator="\n")
        w.writeheader()
        for row in rows:
            w.writerow({k: row.get(k, "") for k in fields})


def sha256(path: Path) -> str:
    if not path.exists() or path.is_dir():
        return ""
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def file_row(repo: Path, rel_path: str) -> Dict[str, Any]:
    p = repo / rel_path
    return {
        "path": rel_path,
        "exists": int(p.exists()),
        "kind": "dir" if p.exists() and p.is_dir() else "file" if p.exists() and p.is_file() else "",
        "bytes": p.stat().st_size if p.exists() and p.is_file() else "",
        "sha256": sha256(p),
        "mutation_in_dd092a": 0,
    }


def candidate_help_markdown(run_id: str, created_utc: str) -> str:
    surface_lines = "\n".join(f"  {cmd}" for cmd, _ in SURFACES)
    detail_sections = "\n\n".join(
        f"### {cmd}\n\n{desc}\n\nRead mode: read-only. This surface must not mutate active catalog data."
        for cmd, desc in SURFACES
    )
    return f"""# DDICT

Candidate HELP topic generated by DD092A.

Run id: `{run_id}`
Created UTC: `{created_utc}`

## Purpose

`DDICT` is the read-only runtime command surface for the active Data Dictionary catalog.

It lets a user inspect catalog tables, catalog objects, fields, tags, relationships, and evidence without mutating DBF, CDX, LMDB, HELP, metadata, or manual artifacts.

## Syntax

```text
{surface_lines}
```

## Surfaces

{detail_sections}

## Notes

- DDICT is read-only over the active Data Dictionary catalog.
- DDICT runtime behavior was proven by DD-089I and captured by DD-090.
- This file is a candidate HELP topic only. DD092A does not install or mutate HELP DATA.
"""


def main() -> int:
    ap = argparse.ArgumentParser(description="DD092A DDICT HELP topic candidate generation")
    ap.add_argument("--repo-root", required=True)
    ap.add_argument("--out-dir", required=True)
    ap.add_argument("--run-id", default="DD092A-ddict-help-topic-candidate-generation-v0")
    ap.add_argument("--dd092-dir", default="docs/datadict/reports/DD092-datadict-help-cmdhelpchk-integration-plan-v0")
    ap.add_argument("--profile", action="append", default=[])
    ap.add_argument("--fail-on-review", action="store_true")
    args = ap.parse_args()

    repo = Path(args.repo_root).resolve()
    out = Path(args.out_dir).resolve()
    out.mkdir(parents=True, exist_ok=True)

    dd092_manifest_path = repo / args.dd092_dir / "dd092_datadict_help_cmdhelpchk_integration_plan_manifest.json"
    dd092 = read_json(dd092_manifest_path)
    dd092_green = int(dd092.get("status") == EXPECTED_DD092_STATUS)

    generated = out / "generated_help_candidates"
    generated.mkdir(parents=True, exist_ok=True)

    created_utc = utc_now()
    help_md = candidate_help_markdown(args.run_id, created_utc)
    help_md_path = generated / "DDICT_HELP_TOPIC_CANDIDATE.md"
    help_md_path.write_text(help_md, encoding="utf-8")

    surface_rows = []
    for order, (syntax, purpose) in enumerate(SURFACES, start=1):
        surface_rows.append({
            "order": order,
            "syntax": syntax,
            "purpose": purpose,
            "candidate_topic": "DDICT",
            "candidate_section": syntax.split()[1] if len(syntax.split()) > 1 else "ROOT",
            "read_only_statement": 1,
            "mutation_now": 0,
        })

    help_topic_row = [{
        "candidate_id": "DDICT_HELP_TOPIC_CANDIDATE",
        "topic": "DDICT",
        "generated_path": str(help_md_path),
        "surface_count": len(SURFACES),
        "install_now": 0,
        "help_data_mutation": 0,
    }]

    protected_rows = [file_row(repo, p) for p in PROTECTED_ARTIFACTS]

    gap_rows = [
        {
            "gap_id": "A1_HELP_FORMAT",
            "question": "Which canonical HELP file/DBF format should receive DDICT later?",
            "candidate_resolution": "Keep this Markdown candidate as reviewed source until HELP/CMDHELPCHK apply lane is authorized.",
            "mutation_now": 0,
        },
        {
            "gap_id": "A2_SUBTOPICS",
            "question": "Should DDICT subcommands become separate HELP topics?",
            "candidate_resolution": "Start with one DDICT topic; split into subtopics only if CMDHELPCHK or HELP doctrine requires it.",
            "mutation_now": 0,
        },
        {
            "gap_id": "A3_RUNTIME_FALLBACK",
            "question": "Should embedded DDICT HELP be removed after HELP topic exists?",
            "candidate_resolution": "No. Keep runtime fallback so DDICT remains self-explaining when HELP DATA is absent.",
            "mutation_now": 0,
        },
    ]

    boundary_rows = [
        {"boundary": "help_topic_candidate_generation_only", "observed": 1, "required": 1, "pass": 1},
        {"boundary": "cxx_source_edits", "observed": 0, "required": 0, "pass": 1},
        {"boundary": "build_file_edits", "observed": 0, "required": 0, "pass": 1},
        {"boundary": "registry_edits", "observed": 0, "required": 0, "pass": 1},
        {"boundary": "active_catalog_mutation", "observed": 0, "required": 0, "pass": 1},
        {"boundary": "dbf_append_replace_delete_pack_zap", "observed": 0, "required": 0, "pass": 1},
        {"boundary": "cdx_lmdb_create_rebuild", "observed": 0, "required": 0, "pass": 1},
        {"boundary": "help_meta_cmdhelpchk_mutation", "observed": 0, "required": 0, "pass": 1},
        {"boundary": "catalog_regeneration", "observed": 0, "required": 0, "pass": 1},
        {"boundary": "manual_row_repair", "observed": 0, "required": 0, "pass": 1},
    ]

    gate_rows = [
        {"gate": "dd092_plan_ready", "expected": EXPECTED_DD092_STATUS, "observed": dd092.get("status", ""), "pass": dd092_green},
        {"gate": "candidate_markdown_written", "expected": 1, "observed": int(help_md_path.exists()), "pass": int(help_md_path.exists())},
        {"gate": "surface_rows_generated", "expected": len(SURFACES), "observed": len(surface_rows), "pass": int(len(surface_rows) == len(SURFACES))},
        {"gate": "help_data_mutation_zero", "expected": 0, "observed": 0, "pass": 1},
        {"gate": "candidate_generation_only", "expected": 1, "observed": 1, "pass": 1},
    ]

    failures = sum(1 for row in gate_rows if int(row["pass"]) != 1)
    status = "DDICT_HELP_TOPIC_CANDIDATE_GENERATED_REVIEW_READY" if failures == 0 else "DDICT_HELP_TOPIC_CANDIDATE_GENERATION_REVIEW"

    next_rows = [
        {
            "next_id": "DD092B",
            "title": "CMDHELPCHK expectation mapping",
            "allowed_scope": "report-only mapping from DDICT surfaces to validation expectations",
        },
        {
            "next_id": "DD092C",
            "title": "guarded HELP/CMDHELPCHK apply package",
            "allowed_scope": "only after explicit authorization and reviewed candidates",
        },
    ]

    write_csv(out / "dd092a_help_topic_candidate_ledger.csv", help_topic_row, ["candidate_id", "topic", "generated_path", "surface_count", "install_now", "help_data_mutation"])
    write_csv(out / "dd092a_surface_section_ledger.csv", surface_rows, ["order", "syntax", "purpose", "candidate_topic", "candidate_section", "read_only_statement", "mutation_now"])
    write_csv(out / "dd092a_gap_review.csv", gap_rows, ["gap_id", "question", "candidate_resolution", "mutation_now"])
    write_csv(out / "dd092a_protected_file_ledger.csv", protected_rows, ["path", "exists", "kind", "bytes", "sha256", "mutation_in_dd092a"])
    write_csv(out / "dd092a_gate_ledger.csv", gate_rows, ["gate", "expected", "observed", "pass"])
    write_csv(out / "dd092a_no_mutation_boundary_ledger.csv", boundary_rows, ["boundary", "observed", "required", "pass"])
    write_csv(out / "dd092a_next_lane_recommendations.csv", next_rows, ["next_id", "title", "allowed_scope"])

    report = f"""# DD092A DDICT HELP Topic Candidate Generation

Run id: `{args.run_id}`
Status: **{status}**
Created UTC: `{created_utc}`

## Purpose

DD092A generates a reviewed candidate HELP topic for the runtime-proven DDICT command surface.

This is candidate generation only. It does not install the topic, mutate HELP DATA, mutate CMDHELPCHK, edit source,
edit command registration, mutate active catalog DBFs, create/rebuild CDX/LMDB, regenerate catalog content, or repair manual rows.

## Preconditions

- DD092 status: `{dd092.get('status', '')}`
- DD092 runtime surfaces: DDICT HELP, STATUS, TABLES, OBJECTS, FIELDS, TAGS, REL, EVIDENCE

## Generated candidate

- Candidate topic: `DDICT`
- Candidate file: `{help_md_path}`
- Surface sections: **{len(surface_rows)}**

## Recommended interpretation

Keep `DDICT HELP` embedded as a runtime fallback. Treat this generated Markdown as the reviewed candidate source for a future HELP/CMDHELPCHK apply lane.

## Boundary

DD092A is candidate-generation/report-only. No protected HELP/CMDHELPCHK/catalog/runtime/manual mutation occurred.
"""

    (out / "DD092A_DDICT_HELP_TOPIC_CANDIDATE_GENERATION_REPORT.md").write_text(report, encoding="utf-8")

    manifest = {
        "contract": "dd092a_ddict_help_topic_candidate_generation_v0",
        "run_id": args.run_id,
        "created_utc": created_utc,
        "status": status,
        "repo_root": str(repo),
        "profiles": args.profile,
        "dd092_status": dd092.get("status", ""),
        "candidate_topic": "DDICT",
        "candidate_markdown": str(help_md_path),
        "surface_count": len(surface_rows),
        "failures": failures,
        "install_now": 0,
        "cxx_source_edits": 0,
        "build_file_edits": 0,
        "registry_edits": 0,
        "active_catalog_mutation": 0,
        "dbf_append_replace_delete_pack_zap": 0,
        "cdx_lmdb_create_rebuild": 0,
        "help_meta_cmdhelpchk_mutation": 0,
        "catalog_regeneration": 0,
        "manual_row_repair": 0,
        "next_recommended_action": "DD092B CMDHELPCHK expectation mapping, then reviewed DD092C apply only if explicitly authorized.",
    }
    write_json(out / "dd092a_ddict_help_topic_candidate_generation_manifest.json", manifest)

    print(f"DD092A DDICT HELP topic candidate generation manifest: {out / 'dd092a_ddict_help_topic_candidate_generation_manifest.json'}")
    print(f"status: {status}; surfaces: {len(surface_rows)}; failures: {failures}")
    return 2 if (args.fail_on_review and failures) else 0


if __name__ == "__main__":
    raise SystemExit(main())
