#pragma once

// Professional ArcticTalk menu command ids.
// Kept separate from foxtalk_ids.hpp so the command desktop can evolve
// without disturbing the existing window/status command id contract.
namespace foxtalk {

enum : unsigned short {
    cmFtSysAbout = 6000,
    cmFtSysVersion,
    cmFtSysStatus,
    cmFtSysPaths,
    cmFtSysColorDefault,
    cmFtSysColorGreen,
    cmFtSysColorAmber,
    cmFtSysShell,
    cmFtSysDotScriptX32,
    cmFtSysDotScriptX64,
    cmFtSysDotScriptSandbox,
    cmFtSysDotScriptInit,
    cmFtSysDotScriptShutdown,
    cmFtSysShowDottalkIni,
    cmFtSysEditDottalkIni,
    cmFtSysEditInitIni,
    cmFtSysEditShutdownIni,
    cmFtSysEditDotScript,
    cmFtSysEditScratch,

    cmFtFileUse,
    cmFtFileClose,
    cmFtFileCloseAll,
    cmFtFileSelect,
    cmFtFileDir,
    cmFtFileImport,
    cmFtFileExport,
    cmFtFileDotScript,

    cmFtWorkSummary,
    cmFtWorkOpenDbf,
    cmFtWorkOpenDir,
    cmFtWorkSave,
    cmFtWorkLoad,
    cmFtWorkClose,
    cmFtWorkArea,
    cmFtWorkDbarea,
    cmFtWorkDbareas,
    cmFtWorkReport,
    cmFtWorkRefresh,

    cmFtErsatzMcc,
    cmFtErsatzPrompt,
    cmFtErsatzWorkspace,
    cmFtErsatzRelAll,
    cmFtErsatzRecord,

    cmFtTableStruct,
    cmFtTableFields,
    cmFtTableStatus,
    cmFtTableMeta,
    cmFtTableValidate,
    cmFtTableDDL,
    cmFtTableShow,
    cmFtTableBufferOn,
    cmFtTableBufferOff,
    cmFtTableStale,
    cmFtTableFresh,
    cmFtTableCommit,
    cmFtTableRollback,

    cmFtRecView,
    cmFtRecDisplay,
    cmFtRecContext,
    cmFtRecGoto,
    cmFtRecTop,
    cmFtRecBottom,
    cmFtRecSkipForward,
    cmFtRecSkipBack,
    cmFtRecAppend,
    cmFtRecAppendBlank,
    cmFtRecEdit,
    cmFtRecReplace,
    cmFtRecDelete,
    cmFtRecRecall,
    cmFtRecPack,
    cmFtRecZapSafe,
    cmFtRecLock,
    cmFtRecUnlock,

    cmFtIdxSetIndex,
    cmFtIdxSetOrder,
    cmFtIdxPhysical,
    cmFtIdxSeek,
    cmFtIdxFind,
    cmFtIdxIndexSeek,
    cmFtIdxAscend,
    cmFtIdxDescend,
    cmFtIdxReindex,
    cmFtIdxBuildLmdb,
    cmFtIdxCnx,
    cmFtIdxCdx,
    cmFtIdxLmdb,

    cmFtListList,
    cmFtListList10,
    cmFtListSmart,
    cmFtListSmartFilter,
    cmFtListDisplay,
    cmFtListCount,
    cmFtListSum,
    cmFtListAverage,
    cmFtListWhere,
    cmFtListSetFilter,
    cmFtListClearFilter,
    cmFtListPredHelp,
    cmFtListPredicates,

    cmFtBrowseCurrent,
    cmFtBrowseSimple,
    cmFtBrowseSmart,
    cmFtBrowseText,
    cmFtBrowseTv,
    cmFtBrowseDev,
    cmFtBrowseRecord,
    cmFtBrowseChildren,
    cmFtBrowseFor,
    cmFtBrowseOrder,

    cmFtRelSet,
    cmFtRelSetAdd,
    cmFtRelOffInto,
    cmFtRelOffAll,
    cmFtRelList,
    cmFtRelListAll,
    cmFtRelRefresh,
    cmFtRelAdd,
    cmFtRelClear,
    cmFtRelSave,
    cmFtRelLoad,
    cmFtRelEnum,

    cmFtTupleAll,
    cmFtTupleFields,
    cmFtTupleArea,
    cmFtTupleMixed,
    cmFtTupleTuptalk,
    cmFtTupleExport,
    cmFtTupleValidate,
    cmFtTupleRelEnum,

    cmFtFuncCalc,
    cmFtFuncEval,
    cmFtFuncCatalog,
    cmFtFuncPredHelp,
    cmFtFuncPredicates,
    cmFtFuncUpper,
    cmFtFuncDate,
    cmFtFuncNumericHelp,
    cmFtFuncStringHelp,

    cmFtCmdHelp,
    cmFtCmdFoxHelp,
    cmFtCmdCatalog,
    cmFtCmdBuildCatalog,
    cmFtCmdValidateCatalog,
    cmFtCmdArgCheck,
    cmFtCmdCommandsHelp,
    cmFtCmdDotScript,
    cmFtCmdTest,
    cmFtCmdShow,
    cmFtCmdDump,
    cmFtCmdSetVar,
    cmFtCmdSetVarBang,
    cmFtCmdSqlVersion,
    cmFtCmdSqlite,
    cmFtCmdSqlExec,
    cmFtCmdSqlSelect,

    cmFtWinClearOutput,

    cmFtHelpMain,
    cmFtHelpCommand,
    cmFtHelpFox,
    cmFtHelpPred,
    cmFtHelpWorkspace,
    cmFtHelpRelations,
    cmFtHelpTuple,
    cmFtHelpBrowser,
    cmFtHelpKeys,
    cmFtHelpAbout
};

} // namespace foxtalk
