# Restore script generated by DD-058
# Run from PowerShell after reviewing paths.

$RepoRoot = "D:\code\ccode"
$BackupRoot = "D:\code\ccode\dottalkpp\data\metadata\datadict_promotion_backups\DD058-controlled-active-catalog-promotion-execute-v0_20260527-203115"

$ActiveCatalog = "D:\code\ccode\dottalkpp\data\metadata\datadict"
$IndexPath = "D:\code\ccode\dottalkpp\data\indexes"
$LmdbPath = "D:\code\ccode\dottalkpp\data\lmdb"

Write-Host "Restoring active catalog from DD-058 backup..."
if (Test-Path "$BackupRoot\active_metadata_datadict") {
  if (Test-Path $ActiveCatalog) { Remove-Item $ActiveCatalog -Recurse -Force }
  Copy-Item "$BackupRoot\active_metadata_datadict" $ActiveCatalog -Recurse -Force
}

Write-Host "Restoring related CDX files..."
if (Test-Path "$BackupRoot\indexes") {
  Get-ChildItem "$BackupRoot\indexes" -Filter "*.cdx" | ForEach-Object {
    Copy-Item $_.FullName (Join-Path $IndexPath $_.Name) -Force
  }
}

Write-Host "Restoring related LMDB environments..."
if (Test-Path "$BackupRoot\lmdb") {
  Get-ChildItem "$BackupRoot\lmdb" -Directory | ForEach-Object {
    $dest = Join-Path $LmdbPath $_.Name
    if (Test-Path $dest) { Remove-Item $dest -Recurse -Force }
    Copy-Item $_.FullName $dest -Recurse -Force
  }
}

Write-Host "DD-058 restore complete. Run post-restore verification before continuing."
