#pragma once
/**
 * @file include/cli/order_nav.hpp
 * @brief Ordered navigation helpers (TOP/BOTTOM/SKIP) for INX/CNX/CDX orderstate.
 *
 * Key goal: avoid building full in-memory recno lists for navigation.
 *
 * INX support:
 * - Reads on-disk "1INX" (legacy variable-length) and "2INX" (fixed-length + pos table).
 * - TOP/BOTTOM are O(1) for 2INX; O(n) scan for 1INX bottom (cached).
 * - SKIP is O(1) for 2INX; O(n) streaming scan (two-pass) for 1INX.
 *
 * CNX/CDX support:
 * - CNX: stopgap builds in-memory ordered recno list by evaluating tag on current table.
 * - CDX: TEMPORARILY uses the same DB-derived ordered recno list as CNX.
 *
 * Rebuild policy:
 * - Indexes generated by REINDEX (INX), REBUILD (CNX), BUILDLMDB (CDX). Navigation only reads.
 *
 * Format-detection improvement:
 * - Uses xindex::fmt::detect(...) instead of "not CNX means INX" style branching.
 * - This keeps navigation extensible for SIX/SNX later without accidental fallthrough.
 */
#include <cstdint>
#include <cstring>
#include <cctype>
#include <algorithm>
#include <sstream>
#include <fstream>
#include <memory>
#include <string>
#include <vector>
#include <unordered_map>
#include <mutex>
#include <filesystem>

#if __has_include(<lmdb.h>)
  #include <lmdb.h>
  #define ORDER_NAV_HAVE_LMDB 1
#else
  #define ORDER_NAV_HAVE_LMDB 0
#endif

#include "xbase.hpp"
#include "cli/order_state.hpp"
#include "cli/order_iterator.hpp"
#include "xindex/index_format_detect.hpp"

namespace order_nav_detail {
namespace fs = std::filesystem;

static inline bool rd_u16(std::ifstream& in, uint16_t& v) {
    unsigned char b[2];
    if (!in.read(reinterpret_cast<char*>(b), 2)) return false;
    v = static_cast<uint16_t>(b[0] | (static_cast<uint16_t>(b[1]) << 8));
    return true;
}

static inline bool rd_u32(std::ifstream& in, uint32_t& v) {
    unsigned char b[4];
    if (!in.read(reinterpret_cast<char*>(b), 4)) return false;
    v = static_cast<uint32_t>(b[0]
        | (static_cast<uint32_t>(b[1]) << 8)
        | (static_cast<uint32_t>(b[2]) << 16)
        | (static_cast<uint32_t>(b[3]) << 24));
    return true;
}

static inline bool rd_i32(std::ifstream& in, int32_t& v) {
    uint32_t u{};
    if (!rd_u32(in, u)) return false;
    v = static_cast<int32_t>(u);
    return true;
}

static inline bool ends_with_ci(const std::string& s, const char* suffix) {
    auto lower = [](unsigned char c) { return static_cast<char>(std::tolower(c)); };
    const std::string suf(suffix);
    if (s.size() < suf.size()) return false;
    for (size_t i = 0; i < suf.size(); ++i) {
        const char a = lower(static_cast<unsigned char>(s[s.size() - suf.size() + i]));
        const char b = lower(static_cast<unsigned char>(suf[i]));
        if (a != b) return false;
    }
    return true;
}

static inline xindex::fmt::IndexFormat detect_fmt(const std::string& path) {
    return xindex::fmt::detect(std::filesystem::path(path));
}

static inline bool is_cnx_like(const std::string& path) {
    const auto f = detect_fmt(path);
    return (f == xindex::fmt::IndexFormat::CNX ||
            f == xindex::fmt::IndexFormat::CDX);
}

static inline bool is_inx_like(const std::string& path) {
    return detect_fmt(path) == xindex::fmt::IndexFormat::INX;
}

static inline bool is_six_or_snx_like(const std::string& path) {
    const auto f = detect_fmt(path);
    return (f == xindex::fmt::IndexFormat::SIX ||
            f == xindex::fmt::IndexFormat::SCX); // SCX is the current enum slot used as SNX/stub.
}

struct InxMeta {
    enum class Kind { Unknown, Inx1, Inx2 };
    Kind kind{Kind::Unknown};
    uint16_t version{0};
    uint16_t keylen{0}; // 2INX only
    std::string exprTok; // stored tag expression token
    uint32_t count{0}; // number of entries
    uint32_t recCountDbf{0}; // DBF recCount snapshot stored in 2INX
    std::uint64_t entries_off{0};
    std::uint64_t pos_off{0};
    fs::file_time_type mtime{};
    std::uint64_t file_size{0};
};

static inline bool read_meta(const fs::path& p, InxMeta& m) {
    m = InxMeta{};
    std::error_code ec{};
    if (!fs::exists(p, ec)) return false;
    m.mtime = fs::last_write_time(p, ec);
    m.file_size = static_cast<std::uint64_t>(fs::file_size(p, ec));
    std::ifstream in(p, std::ios::binary);
    if (!in) return false;
    char magic[4]{};
    if (!in.read(magic, 4)) return false;
    if (std::memcmp(magic, "1INX", 4) == 0) {
        m.kind = InxMeta::Kind::Inx1;
        if (!rd_u16(in, m.version)) return false;
        uint16_t exprLen{};
        if (!rd_u16(in, exprLen)) return false;
        m.exprTok.resize(exprLen);
        if (!in.read(m.exprTok.data(), static_cast<std::streamsize>(exprLen))) return false;
        if (!rd_u32(in, m.count)) return false;
        m.entries_off = static_cast<std::uint64_t>(in.tellg());
        return true;
    }
    if (std::memcmp(magic, "2INX", 4) == 0) {
        m.kind = InxMeta::Kind::Inx2;
        if (!rd_u16(in, m.version)) return false;
        if (!rd_u16(in, m.keylen)) return false;
        uint16_t exprLen{};
        if (!rd_u16(in, exprLen)) return false;
        m.exprTok.resize(exprLen);
        if (!in.read(m.exprTok.data(), static_cast<std::streamsize>(exprLen))) return false;
        if (!rd_u32(in, m.count)) return false;
        if (!rd_u32(in, m.recCountDbf)) return false;
        m.entries_off = static_cast<std::uint64_t>(in.tellg());
        const std::uint64_t entry_sz = static_cast<std::uint64_t>(m.keylen) + 4ULL;
        m.pos_off = m.entries_off + entry_sz * static_cast<std::uint64_t>(m.count);
        return true;
    }
    return false;
}

struct Endpoints {
    int32_t first{0};
    int32_t last{0};
    fs::file_time_type mtime{};
    std::uint64_t file_size{0};
};

static inline std::mutex& endpoints_mtx() {
    static std::mutex mtx;
    return mtx;
}

static inline std::unordered_map<std::string, Endpoints>& endpoints_cache() {
    static std::unordered_map<std::string, Endpoints> c;
    return c;
}

static inline bool cache_get_endpoints(const fs::path& p, const InxMeta& m, Endpoints& out) {
    std::lock_guard<std::mutex> lk(endpoints_mtx());
    auto& c = endpoints_cache();
    auto it = c.find(p.string());
    if (it == c.end()) return false;
    if (it->second.file_size != m.file_size) return false;
    if (it->second.mtime != m.mtime) return false;
    out = it->second;
    return true;
}

static inline void cache_put_endpoints(const fs::path& p, const InxMeta& m, const Endpoints& ep) {
    std::lock_guard<std::mutex> lk(endpoints_mtx());
    Endpoints tmp = ep;
    tmp.file_size = m.file_size;
    tmp.mtime = m.mtime;
    endpoints_cache()[p.string()] = tmp;
}

static inline void cache_invalidate_path(const fs::path& p) {
    std::lock_guard<std::mutex> lk(endpoints_mtx());
    endpoints_cache().erase(p.string());
}

static inline bool inx1_read_first_last(const fs::path& p, const InxMeta& m, int32_t& out_first, int32_t& out_last) {
    Endpoints ep{};
    if (cache_get_endpoints(p, m, ep)) {
        out_first = ep.first;
        out_last = ep.last;
        return (out_first != 0 && out_last != 0);
    }
    std::ifstream in(p, std::ios::binary);
    if (!in) return false;
    in.seekg(static_cast<std::streamoff>(m.entries_off), std::ios::beg);
    uint32_t cnt = m.count;
    uint32_t recno_u = 0;
    out_first = 0;
    out_last = 0;
    for (uint32_t i = 0; i < cnt; ++i) {
        uint16_t klen{};
        if (!rd_u16(in, klen)) return false;
        if (!in.seekg(static_cast<std::streamoff>(klen), std::ios::cur)) return false;
        if (!rd_u32(in, recno_u)) return false;
        if (i == 0) out_first = static_cast<int32_t>(recno_u);
        out_last = static_cast<int32_t>(recno_u);
    }
    ep.first = out_first;
    ep.last = out_last;
    ep.mtime = m.mtime;
    ep.file_size = m.file_size;
    cache_put_endpoints(p, m, ep);
    return (out_first != 0 && out_last != 0);
}

static inline bool inx2_read_first_last(const fs::path& p, const InxMeta& m, int32_t& out_first, int32_t& out_last) {
    Endpoints ep{};
    if (cache_get_endpoints(p, m, ep)) {
        out_first = ep.first;
        out_last = ep.last;
        return (out_first != 0 && out_last != 0);
    }
    if (m.count == 0) return false;
    std::ifstream in(p, std::ios::binary);
    if (!in) return false;
    const std::uint64_t entry_sz = static_cast<std::uint64_t>(m.keylen) + 4ULL;
    in.seekg(static_cast<std::streamoff>(m.entries_off + m.keylen), std::ios::beg);
    uint32_t rn_first = 0;
    if (!rd_u32(in, rn_first)) return false;
    const std::uint64_t last_off = m.entries_off + entry_sz * (static_cast<std::uint64_t>(m.count) - 1ULL) + m.keylen;
    in.seekg(static_cast<std::streamoff>(last_off), std::ios::beg);
    uint32_t rn_last = 0;
    if (!rd_u32(in, rn_last)) return false;
    out_first = static_cast<int32_t>(rn_first);
    out_last = static_cast<int32_t>(rn_last);
    ep.first = out_first;
    ep.last = out_last;
    ep.mtime = m.mtime;
    ep.file_size = m.file_size;
    cache_put_endpoints(p, m, ep);
    return (out_first != 0 && out_last != 0);
}

static inline bool read_first_last(const fs::path& p, const InxMeta& m, int32_t& out_first, int32_t& out_last) {
    if (m.kind == InxMeta::Kind::Inx1) return inx1_read_first_last(p, m, out_first, out_last);
    if (m.kind == InxMeta::Kind::Inx2) return inx2_read_first_last(p, m, out_first, out_last);
    return false;
}

static inline bool load_inx_recnos(const std::string& inx_path, int32_t maxRecno, std::vector<uint32_t>& out) {
    out.clear();
    std::ifstream f(inx_path, std::ios::binary);
    if (!f) return false;
    auto rd_u16_local = [&](uint16_t& v)->bool { return rd_u16(f, v); };
    auto rd_u32_local = [&](uint32_t& v)->bool { return rd_u32(f, v); };
    char magic[4]{};
    if (!f.read(magic, 4)) return false;
    std::string mg(magic, magic + 4);
    if (mg == "2INX") {
        uint16_t ver = 0, keylen = 0, exprLen = 0;
        uint32_t count = 0, recCountDbf = 0;
        if (!rd_u16_local(ver)) return false;
        if (!rd_u16_local(keylen)) return false;
        if (!rd_u16_local(exprLen)) return false;
        if (exprLen > 0) f.seekg(exprLen, std::ios::cur);
        if (!rd_u32_local(count)) return false;
        if (!rd_u32_local(recCountDbf)) return false;
        (void)ver; (void)recCountDbf;
        const std::uint64_t entry_sz = static_cast<std::uint64_t>(keylen) + 4ULL;
        const std::uint64_t entries_off = static_cast<std::uint64_t>(f.tellg());
        f.seekg(static_cast<std::streamoff>(entries_off + static_cast<std::uint64_t>(keylen)), std::ios::beg);
        out.reserve(static_cast<size_t>(count));
        for (uint32_t i = 0; i < count; ++i) {
            if (!f.seekg(static_cast<std::streamoff>(entry_sz * i), std::ios::cur)) return false;
            uint32_t rn = 0;
            if (!rd_u32_local(rn)) return false;
            if (rn >= 1 && rn <= static_cast<uint32_t>(maxRecno)) out.push_back(rn);
            f.seekg(static_cast<std::streamoff>(entries_off + static_cast<std::uint64_t>(keylen)), std::ios::beg);
        }
        return true;
    }
    if (mg == "1INX") {
        uint16_t ver = 0, exprLen = 0;
        uint32_t count = 0;
        if (!rd_u16_local(ver)) return false;
        if (!rd_u16_local(exprLen)) return false;
        if (exprLen > 0) f.seekg(exprLen, std::ios::cur);
        if (!rd_u32_local(count)) return false;
        (void)ver;
        out.reserve(static_cast<size_t>(count));
        for (uint32_t i = 0; i < count; ++i) {
            uint16_t klen = 0;
            if (!rd_u16_local(klen)) return false;
            if (klen > 0) f.seekg(klen, std::ios::cur);
            uint32_t rn = 0;
            if (!rd_u32_local(rn)) return false;
            if (rn >= 1 && rn <= static_cast<uint32_t>(maxRecno)) out.push_back(rn);
        }
        return true;
    }
    return false;
}

static inline bool build_cnx_recnos_from_db(xbase::DbArea& A,
                                           const std::string& tagTok,
                                           std::vector<uint32_t>& out)
{
    out.clear();
    if (!A.isOpen()) return false;
    const int32_t saved_recno = A.recno();
    const int32_t saved_total = A.recCount();
    const bool saved_ok = (saved_recno >= 1 && saved_recno <= saved_total);
    auto trim_copy = [](const std::string& s)->std::string {
        size_t a = 0, b = s.size();
        while (a < b && std::isspace(static_cast<unsigned char>(s[a]))) ++a;
        while (b > a && std::isspace(static_cast<unsigned char>(s[b-1]))) --b;
        return s.substr(a, b - a);
    };
    auto upper_copy = [](std::string s)->std::string {
        for (char& c : s) c = static_cast<char>(std::toupper(static_cast<unsigned char>(c)));
        return s;
    };
    auto ieq = [](const std::string& a, const std::string& b)->bool {
        if (a.size() != b.size()) return false;
        for (size_t i = 0; i < a.size(); ++i) {
            if (std::toupper(static_cast<unsigned char>(a[i])) !=
                std::toupper(static_cast<unsigned char>(b[i]))) return false;
        }
        return true;
    };
    const std::string tok = trim_copy(tagTok);
    if (tok.empty()) {
        if (saved_ok) { (void)A.gotoRec(saved_recno); (void)A.readCurrent(); }
        return false;
    }
    const auto& Fs = A.fields();
    int fldIdx = -1;
    if (tok.size() >= 2 && tok[0] == '#') {
        try {
            fldIdx = std::stoi(tok.substr(1));
        } catch (...) {
            fldIdx = -1;
        }
    } else {
        for (int i = 0; i < static_cast<int>(Fs.size()); ++i) {
            if (ieq(trim_copy(Fs[static_cast<size_t>(i)].name), tok)) {
                fldIdx = i + 1;
                break;
            }
        }
    }
    if (fldIdx < 1 || fldIdx > static_cast<int>(Fs.size())) {
        if (saved_ok) { (void)A.gotoRec(saved_recno); (void)A.readCurrent(); }
        return false;
    }
    const auto& fdef = Fs[static_cast<size_t>(fldIdx - 1)];
    const uint16_t keylen = static_cast<uint16_t>(fdef.length);
    const char ftype = fdef.type;
    struct Entry { std::string key; uint32_t recno; };
    std::vector<Entry> ents;
    ents.reserve(static_cast<size_t>(std::max(0, A.recCount())));
    const int32_t total = A.recCount();
    for (int32_t rn = 1; rn <= total; ++rn) {
        if (!A.gotoRec(rn)) continue;
        if (!A.readCurrent()) continue;
        if (A.isDeleted()) continue;
        std::string k = A.get(fldIdx);
        if (ftype == 'C' || ftype == 'c') {
            k = upper_copy(k);
        }
        if (k.size() > keylen) k.resize(keylen);
        if (k.size() < keylen) k.append(static_cast<size_t>(keylen - k.size()), ' ');
        ents.push_back(Entry{ std::move(k), static_cast<uint32_t>(rn) });
    }
    std::sort(ents.begin(), ents.end(),
        [](const Entry& a, const Entry& b){
            if (a.key == b.key) return a.recno < b.recno;
            return a.key < b.key;
        });
    out.reserve(ents.size());
    for (const auto& e : ents) out.push_back(e.recno);
    if (saved_ok) { (void)A.gotoRec(saved_recno); (void)A.readCurrent(); }
    return true;
}

#if ORDER_NAV_HAVE_LMDB
static inline bool build_cdx_recnos_from_lmdb(const std::string& cdx_path,
                                             const std::string& tag_upper,
                                             int32_t maxRecno,
                                             std::vector<uint32_t>& out)
{
    out.clear();
    if (cdx_path.empty() || tag_upper.empty() || maxRecno <= 0) return false;

    fs::path envDir = fs::path(cdx_path);
    envDir += ".d";

    std::error_code ec{};
    if (!fs::exists(envDir, ec) || !fs::is_directory(envDir, ec)) return false;
    if (!fs::exists(envDir / "data.mdb", ec)) return false;

    MDB_env* env = nullptr;
    MDB_txn* txn = nullptr;
    MDB_dbi dbi = 0;
    MDB_cursor* cur = nullptr;

    auto cleanup = [&]() {
        if (cur) { mdb_cursor_close(cur); cur = nullptr; }
        if (txn) { mdb_txn_abort(txn); txn = nullptr; }
        if (env) { mdb_env_close(env); env = nullptr; }
    };

    int rc = mdb_env_create(&env);
    if (rc != MDB_SUCCESS) { cleanup(); return false; }

    rc = mdb_env_set_maxdbs(env, 1024);
    if (rc != MDB_SUCCESS) { cleanup(); return false; }

    rc = mdb_env_open(env, envDir.string().c_str(), MDB_RDONLY, 0664);
    if (rc != MDB_SUCCESS) { cleanup(); return false; }

    rc = mdb_txn_begin(env, nullptr, MDB_RDONLY, &txn);
    if (rc != MDB_SUCCESS) { cleanup(); return false; }

    rc = mdb_dbi_open(txn, tag_upper.c_str(), 0, &dbi);
    if (rc != MDB_SUCCESS) { cleanup(); return false; }

    rc = mdb_cursor_open(txn, dbi, &cur);
    if (rc != MDB_SUCCESS) { cleanup(); return false; }

    MDB_val k{}, v{};
    rc = mdb_cursor_get(cur, &k, &v, MDB_FIRST);
    if (rc == MDB_NOTFOUND) { cleanup(); return false; }
    if (rc != MDB_SUCCESS) { cleanup(); return false; }

    out.reserve(static_cast<size_t>(maxRecno));

    auto parse_recno = [&](const MDB_val& vv, uint32_t& rn_out)->bool {
        rn_out = 0;
        if (vv.mv_size == 4) {
            const unsigned char* b = static_cast<const unsigned char*>(vv.mv_data);
            rn_out = static_cast<uint32_t>(b[0]
                | (static_cast<uint32_t>(b[1]) << 8)
                | (static_cast<uint32_t>(b[2]) << 16)
                | (static_cast<uint32_t>(b[3]) << 24));
            return true;
        }
        if (vv.mv_size == 8) {
            const unsigned char* b = static_cast<const unsigned char*>(vv.mv_data);
            std::uint64_t u = static_cast<std::uint64_t>(b[0])
                | (static_cast<std::uint64_t>(b[1]) << 8)
                | (static_cast<std::uint64_t>(b[2]) << 16)
                | (static_cast<std::uint64_t>(b[3]) << 24)
                | (static_cast<std::uint64_t>(b[4]) << 32)
                | (static_cast<std::uint64_t>(b[5]) << 40)
                | (static_cast<std::uint64_t>(b[6]) << 48)
                | (static_cast<std::uint64_t>(b[7]) << 56);
            rn_out = static_cast<uint32_t>(u);
            return true;
        }
        const char* p = static_cast<const char*>(vv.mv_data);
        const char* e = p + vv.mv_size;
        std::uint64_t u = 0;
        bool any = false;
        for (; p < e; ++p) {
            unsigned char c = static_cast<unsigned char>(*p);
            if (c < '0' || c > '9') break;
            any = true;
            u = (u * 10ULL) + static_cast<std::uint64_t>(c - '0');
            if (u > 0xFFFFFFFFULL) break;
        }
        if (!any) return false;
        rn_out = static_cast<uint32_t>(u);
        return true;
    };

    while (true) {
        uint32_t rn = 0;
        if (parse_recno(v, rn)) {
            if (rn >= 1 && rn <= static_cast<uint32_t>(maxRecno)) {
                out.push_back(rn);
            }
        }
        rc = mdb_cursor_get(cur, &k, &v, MDB_NEXT);
        if (rc == MDB_NOTFOUND) break;
        if (rc != MDB_SUCCESS) { cleanup(); return false; }
    }

    cleanup();
    return !out.empty();
}

// Read a single ordered endpoint (first or last logical index entry) directly
// from the LMDB index using MDB_FIRST / MDB_LAST. This is O(1) in the number of
// records and does NOT scan the DBF or build any in-memory recno list. It is the
// correct primitive for CDX TOP/BOTTOM on large tables.
//
// wantLast == false -> MDB_FIRST (smallest key)
// wantLast == true  -> MDB_LAST  (largest key)
//
// If the endpoint entry references a stale recno (> maxRecno), the cursor steps
// inward until it finds a recno within [1, maxRecno].
static inline bool cdx_endpoint_from_lmdb(const std::string& cdx_path,
                                          const std::string& tag_upper,
                                          int32_t maxRecno,
                                          bool wantLast,
                                          int32_t& out_recno)
{
    out_recno = 0;
    if (cdx_path.empty() || tag_upper.empty() || maxRecno <= 0) return false;

    fs::path envDir = fs::path(cdx_path);
    envDir += ".d";

    std::error_code ec{};
    if (!fs::exists(envDir, ec) || !fs::is_directory(envDir, ec)) return false;
    if (!fs::exists(envDir / "data.mdb", ec)) return false;

    MDB_env* env = nullptr;
    MDB_txn* txn = nullptr;
    MDB_dbi dbi = 0;
    MDB_cursor* cur = nullptr;

    auto cleanup = [&]() {
        if (cur) { mdb_cursor_close(cur); cur = nullptr; }
        if (txn) { mdb_txn_abort(txn); txn = nullptr; }
        if (env) { mdb_env_close(env); env = nullptr; }
    };

    int rc = mdb_env_create(&env);
    if (rc != MDB_SUCCESS) { cleanup(); return false; }
    rc = mdb_env_set_maxdbs(env, 1024);
    if (rc != MDB_SUCCESS) { cleanup(); return false; }
    rc = mdb_env_open(env, envDir.string().c_str(), MDB_RDONLY, 0664);
    if (rc != MDB_SUCCESS) { cleanup(); return false; }
    rc = mdb_txn_begin(env, nullptr, MDB_RDONLY, &txn);
    if (rc != MDB_SUCCESS) { cleanup(); return false; }
    rc = mdb_dbi_open(txn, tag_upper.c_str(), 0, &dbi);
    if (rc != MDB_SUCCESS) { cleanup(); return false; }
    rc = mdb_cursor_open(txn, dbi, &cur);
    if (rc != MDB_SUCCESS) { cleanup(); return false; }

    // Identical value-decode contract as build_cdx_recnos_from_lmdb(): the recno
    // is stored in the value (4/8-byte LE, or ASCII digits) for both DUPSORT and
    // composite-key layouts, so reading the value is sufficient at either end.
    auto parse_recno = [&](const MDB_val& vv, uint32_t& rn_out)->bool {
        rn_out = 0;
        if (vv.mv_size == 4) {
            const unsigned char* b = static_cast<const unsigned char*>(vv.mv_data);
            rn_out = static_cast<uint32_t>(b[0]
                | (static_cast<uint32_t>(b[1]) << 8)
                | (static_cast<uint32_t>(b[2]) << 16)
                | (static_cast<uint32_t>(b[3]) << 24));
            return true;
        }
        if (vv.mv_size == 8) {
            const unsigned char* b = static_cast<const unsigned char*>(vv.mv_data);
            std::uint64_t u = static_cast<std::uint64_t>(b[0])
                | (static_cast<std::uint64_t>(b[1]) << 8)
                | (static_cast<std::uint64_t>(b[2]) << 16)
                | (static_cast<std::uint64_t>(b[3]) << 24)
                | (static_cast<std::uint64_t>(b[4]) << 32)
                | (static_cast<std::uint64_t>(b[5]) << 40)
                | (static_cast<std::uint64_t>(b[6]) << 48)
                | (static_cast<std::uint64_t>(b[7]) << 56);
            rn_out = static_cast<uint32_t>(u);
            return true;
        }
        const char* p = static_cast<const char*>(vv.mv_data);
        const char* e = p + vv.mv_size;
        std::uint64_t u = 0;
        bool any = false;
        for (; p < e; ++p) {
            unsigned char c = static_cast<unsigned char>(*p);
            if (c < '0' || c > '9') break;
            any = true;
            u = (u * 10ULL) + static_cast<std::uint64_t>(c - '0');
            if (u > 0xFFFFFFFFULL) break;
        }
        if (!any) return false;
        rn_out = static_cast<uint32_t>(u);
        return true;
    };

    MDB_val k{}, v{};
    rc = mdb_cursor_get(cur, &k, &v, wantLast ? MDB_LAST : MDB_FIRST);

    std::uint64_t guard = 0;
    const std::uint64_t guard_max = static_cast<std::uint64_t>(maxRecno) + 16ULL;
    while (rc == MDB_SUCCESS) {
        uint32_t rn = 0;
        if (parse_recno(v, rn) && rn >= 1 && rn <= static_cast<uint32_t>(maxRecno)) {
            out_recno = static_cast<int32_t>(rn);
            cleanup();
            return true;
        }
        if (++guard > guard_max) break;
        rc = mdb_cursor_get(cur, &k, &v, wantLast ? MDB_PREV : MDB_NEXT);
    }

    cleanup();
    return false;
}
#endif

struct CnxCache {
    xbase::DbArea* area{nullptr};
    std::string tag;
    std::int64_t recCount{0};                              // RECNO64 O2
    std::vector<std::uint64_t> recnos;                     // RECNO64 O2: 64-bit ordered recnos
    std::unordered_map<std::uint64_t, std::int64_t> pos;   // recno -> ordinal position
};

static inline CnxCache& cnx_cache_singleton() {
    static CnxCache c;
    return c;
}

static inline void cnx_cache_invalidate() {
    CnxCache& c = cnx_cache_singleton();
    c.area = nullptr;
    c.tag.clear();
    c.recCount = 0;
    c.recnos.clear();
    c.pos.clear();
}

static inline bool cnx_cache_build(CnxCache& cache, xbase::DbArea& area, const std::string& tagName)
{
    if (!area.isOpen()) return false;
    const std::int64_t N = static_cast<std::int64_t>(area.recCount64());
    if (cache.area == &area &&
        cache.tag == tagName &&
        cache.recCount == N &&
        !cache.recnos.empty())
    {
        return true;
    }
    cache.area = &area;
    cache.tag = tagName;
    cache.recCount = N;
    cache.recnos.clear();
    cache.pos.clear();

    // build_cnx_recnos_from_db stays 32-bit (CNX is a V32 format, and the builder is
    // shared with db_tuple_stream). Widen its recnos up into the 64-bit cache here.
    std::vector<uint32_t> tmp32;
    if (!build_cnx_recnos_from_db(area, tagName, tmp32))
        return false;
    cache.recnos.assign(tmp32.begin(), tmp32.end());

    cache.pos.reserve(cache.recnos.size());
    for (std::int64_t i = 0; i < static_cast<std::int64_t>(cache.recnos.size()); ++i) {
        cache.pos[cache.recnos[static_cast<size_t>(i)]] = i;
    }
    return !cache.recnos.empty();
}

// CDX ordered cache built directly from the LMDB index (already key-sorted), so
// there is no DBF scan and no key sort. This is the correct source for CDX SKIP;
// the CNX DB-scan builder (cnx_cache_build) is reserved for 32-bit CNX flavors.
// Returns false if LMDB is unavailable so callers can fall back safely.
static inline bool cdx_cache_build(CnxCache& cache,
                                   xbase::DbArea& area,
                                   const std::string& tagName,
                                   const std::string& cdxPath)
{
    if (!area.isOpen()) return false;
    const std::int64_t N = static_cast<std::int64_t>(area.recCount64());
    if (cache.area == &area &&
        cache.tag == tagName &&
        cache.recCount == N &&
        !cache.recnos.empty())
    {
        return true;
    }
    cache.area = &area;
    cache.tag = tagName;
    cache.recCount = N;
    cache.recnos.clear();
    cache.pos.clear();
    (void)cdxPath;

    // Ascending index order via the IndexManager backend cursor. This resolves
    // the LMDB env correctly (unlike a raw <cdx>.d guess) and avoids scanning +
    // sorting the DBF. order_collect_recnos_asc always yields ascending index
    // order, which is what the position/step math below expects.
    std::vector<std::uint64_t> tmp;
    if (!cli::order_collect_recnos_asc(area, tmp, nullptr, nullptr) || tmp.empty())
        return false;

    cache.recnos.reserve(tmp.size());
    for (std::uint64_t rn : tmp) {
        if (rn >= 1 && rn <= static_cast<std::uint64_t>(N))
            cache.recnos.push_back(rn);
    }

    cache.pos.reserve(cache.recnos.size());
    for (std::int64_t i = 0; i < static_cast<std::int64_t>(cache.recnos.size()); ++i) {
        cache.pos[cache.recnos[static_cast<size_t>(i)]] = i;
    }
    return !cache.recnos.empty();
}

} // namespace order_nav_detail

static inline bool order_first_recno(xbase::DbArea& area, std::int64_t& out_recno) {
    out_recno = 0;
    if (!area.isOpen()) return false;
    if (!orderstate::hasOrder(area)) return false;
    const std::string path = orderstate::orderName(area);

    switch (order_nav_detail::detect_fmt(path)) {
    case xindex::fmt::IndexFormat::CDX: {
        // CDX is the LMDB front end (64-bit DBF flavors). Stream the backend
        // cursor (IndexManager resolves the LMDB env via SET PATH LMDB) and stop
        // at the first record in display order. One index op, independent of
        // table size. Only fall back to the DB-scan cache if the cursor is
        // unavailable.
        const std::string tagName = orderstate::activeTag(area);
        if (tagName.empty()) return false;

        std::int64_t rn = 0;
        cli::order_stream_display(area, /*reverse=*/false,
            [&](std::uint64_t recno) -> bool {
                rn = static_cast<std::int64_t>(recno);
                return false; // stop at the first record
            });
        if (rn >= 1 && rn <= static_cast<std::int64_t>(area.recCount64())) { out_recno = rn; return true; }

        const bool asc = orderstate::isAscending(area);
        auto& cache = order_nav_detail::cnx_cache_singleton();
        if (!order_nav_detail::cnx_cache_build(cache, area, tagName)) return false;
        if (cache.recnos.empty()) return false;
        out_recno = asc ? static_cast<std::int64_t>(cache.recnos.front())
                        : static_cast<std::int64_t>(cache.recnos.back());
        return (out_recno != 0);
    }
    case xindex::fmt::IndexFormat::CNX: {
        const std::string tagName = orderstate::activeTag(area);
        if (tagName.empty()) return false;
        auto& cache = order_nav_detail::cnx_cache_singleton();
        if (!order_nav_detail::cnx_cache_build(cache, area, tagName)) return false;
        if (cache.recnos.empty()) return false;
        const bool asc = orderstate::isAscending(area);
        out_recno = asc ? static_cast<std::int64_t>(cache.recnos.front())
                        : static_cast<std::int64_t>(cache.recnos.back());
        return (out_recno != 0);
    }
    case xindex::fmt::IndexFormat::INX: {
        order_nav_detail::InxMeta meta{};
        const order_nav_detail::fs::path p(path);
        if (!order_nav_detail::read_meta(p, meta)) return false;
        int32_t first{}, last{};
        if (!order_nav_detail::read_first_last(p, meta, first, last)) return false;
        const bool asc = orderstate::isAscending(area);
        out_recno = asc ? first : last;
        return (out_recno != 0);
    }
    case xindex::fmt::IndexFormat::SIX:
        // SIX is recognized but not implemented.
        return false;
    case xindex::fmt::IndexFormat::SCX:
        // SNX placeholder/stub; see note in order_skip().
        return false;
    case xindex::fmt::IndexFormat::Unknown:
    default:
        return false;
    }
}

static inline bool order_last_recno(xbase::DbArea& area, std::int64_t& out_recno) {
    out_recno = 0;
    if (!area.isOpen()) return false;
    if (!orderstate::hasOrder(area)) return false;
    const std::string path = orderstate::orderName(area);

    switch (order_nav_detail::detect_fmt(path)) {
    case xindex::fmt::IndexFormat::CDX: {
        // CDX is the LMDB front end (64-bit DBF flavors). Stream the backend
        // cursor in reverse display order and stop at the first record, i.e. the
        // last record in display order. One index op, independent of table size.
        const std::string tagName = orderstate::activeTag(area);
        if (tagName.empty()) return false;

        std::int64_t rn = 0;
        cli::order_stream_display(area, /*reverse=*/true,
            [&](std::uint64_t recno) -> bool {
                rn = static_cast<std::int64_t>(recno);
                return false; // stop at the last record
            });
        if (rn >= 1 && rn <= static_cast<std::int64_t>(area.recCount64())) { out_recno = rn; return true; }

        const bool asc = orderstate::isAscending(area);
        auto& cache = order_nav_detail::cnx_cache_singleton();
        if (!order_nav_detail::cnx_cache_build(cache, area, tagName)) return false;
        if (cache.recnos.empty()) return false;
        out_recno = asc ? static_cast<std::int64_t>(cache.recnos.back())
                        : static_cast<std::int64_t>(cache.recnos.front());
        return (out_recno != 0);
    }
    case xindex::fmt::IndexFormat::CNX: {
        const std::string tagName = orderstate::activeTag(area);
        if (tagName.empty()) return false;
        auto& cache = order_nav_detail::cnx_cache_singleton();
        if (!order_nav_detail::cnx_cache_build(cache, area, tagName)) return false;
        if (cache.recnos.empty()) return false;
        const bool asc = orderstate::isAscending(area);
        out_recno = asc ? static_cast<std::int64_t>(cache.recnos.back())
                        : static_cast<std::int64_t>(cache.recnos.front());
        return (out_recno != 0);
    }
    case xindex::fmt::IndexFormat::INX: {
        order_nav_detail::InxMeta meta{};
        const order_nav_detail::fs::path p(path);
        if (!order_nav_detail::read_meta(p, meta)) return false;
        int32_t first{}, last{};
        if (!order_nav_detail::read_first_last(p, meta, first, last)) return false;
        const bool asc = orderstate::isAscending(area);
        out_recno = asc ? last : first;
        return (out_recno != 0);
    }
    case xindex::fmt::IndexFormat::SIX:
        // SIX is recognized but not implemented.
        return false;
    case xindex::fmt::IndexFormat::SCX:
        // SNX placeholder/stub; see note in order_skip().
        return false;
    case xindex::fmt::IndexFormat::Unknown:
    default:
        return false;
    }
}

static inline bool order_top(xbase::DbArea& area) {
    if (!area.isOpen()) return false;
    std::int64_t rn{};
    if (order_first_recno(area, rn) && rn >= 1 && rn <= static_cast<std::int64_t>(area.recCount64())) {
        if (!area.gotoRec64(static_cast<std::uint64_t>(rn))) return false;
        return area.readCurrent();
    }
    if (!area.top()) return false;
    return area.readCurrent();
}

static inline bool order_bottom(xbase::DbArea& area) {
    if (!area.isOpen()) return false;
    std::int64_t rn{};
    if (order_last_recno(area, rn) && rn >= 1 && rn <= static_cast<std::int64_t>(area.recCount64())) {
        if (!area.gotoRec64(static_cast<std::uint64_t>(rn))) return false;
        return area.readCurrent();
    }
    if (!area.bottom()) return false;
    return area.readCurrent();
}

static inline bool order_skip(xbase::DbArea& area, int delta) {
    if (!area.isOpen()) return false;
    if (delta == 0) return area.readCurrent();

    if (!orderstate::hasOrder(area)) {
        if (!area.skip(delta)) return false;
        return area.readCurrent();
    }

    const std::string path = orderstate::orderName(area);

    switch (order_nav_detail::detect_fmt(path)) {
    case xindex::fmt::IndexFormat::CDX: {
        // CDX is the LMDB front end.
        const std::string tag = orderstate::activeTag(area);
        if (tag.empty()) return false;

        const bool asc = orderstate::isAscending(area);
        const int delta_eff = asc ? delta : -delta;

        // Fast path: a single ordered cursor step from the current record --
        // seek the current (key,recno) and step in the LMDB index. No position
        // map, no DBF scan; O(log n). This is what makes the FIRST ordered SKIP
        // instant.
        {
            std::int64_t rn = 0;
            const cli::OrderStep st = cli::order_step_cdx(area, delta_eff, rn);
            if (st == cli::OrderStep::Moved) {
                if (rn < 1 || rn > static_cast<std::int64_t>(area.recCount64())) return false;
                if (!area.gotoRec64(static_cast<std::uint64_t>(rn))) return false;
                return area.readCurrent();
            }
            // TODO(RECNO64 M5): the position-map fallback cache below is still 32-bit
            // (build_cdx_recnos_from_lmdb / CnxCache.recnos / uint32 rn); widen with O2.
            if (st == cli::OrderStep::Boundary) {
                return false; // at an order endpoint; no movement (do NOT fall back)
            }
            // Unavailable -> fall through to the position-map cache.
        }

        // Fallback: position-map cache built from the ascending index cursor
        // (first use materializes once), then the DB-scan cache if even that is
        // unavailable.
        auto& cache = order_nav_detail::cnx_cache_singleton();
        bool built = order_nav_detail::cdx_cache_build(cache, area, tag, path);
        if (!built) {
            if (!order_nav_detail::cnx_cache_build(cache, area, tag)) return false;
        }
        if (cache.recnos.empty()) return false;

        const std::int64_t cur = static_cast<std::int64_t>(area.recno64());
        if (cur < 1 || cur > static_cast<std::int64_t>(area.recCount64())) return false;

        auto it = cache.pos.find(static_cast<std::uint64_t>(cur));
        if (it == cache.pos.end()) return false;

        // Partial-to-boundary (matches the cursor step and xBase SKIP-to-EOF).
        std::int64_t next = it->second + delta_eff;
        const std::int64_t last = static_cast<std::int64_t>(cache.recnos.size()) - 1;
        if (next < 0) next = 0;
        if (next > last) next = last;
        if (next == it->second) return false; // already at the boundary; no move

        const std::int64_t rn = static_cast<std::int64_t>(cache.recnos[static_cast<size_t>(next)]);
        if (rn < 1 || rn > static_cast<std::int64_t>(area.recCount64())) return false;
        if (!area.gotoRec64(static_cast<std::uint64_t>(rn))) return false;
        return area.readCurrent();
    }

    case xindex::fmt::IndexFormat::CNX: {
        const std::string tag = orderstate::activeTag(area);
        if (tag.empty()) return false;

        auto& cache = order_nav_detail::cnx_cache_singleton();
        if (!order_nav_detail::cnx_cache_build(cache, area, tag) || cache.recnos.empty()) return false;

        const bool asc = orderstate::isAscending(area);
        const int delta_eff = asc ? delta : -delta;

        const std::int64_t cur = static_cast<std::int64_t>(area.recno64());
        if (cur < 1 || cur > static_cast<std::int64_t>(area.recCount64())) return false;

        auto it = cache.pos.find(static_cast<std::uint64_t>(cur));
        if (it == cache.pos.end()) return false;

        // Partial-to-boundary (matches the cursor step and xBase SKIP-to-EOF).
        std::int64_t next = it->second + delta_eff;
        const std::int64_t last = static_cast<std::int64_t>(cache.recnos.size()) - 1;
        if (next < 0) next = 0;
        if (next > last) next = last;
        if (next == it->second) return false; // already at the boundary; no move

        const std::int64_t rn = static_cast<std::int64_t>(cache.recnos[static_cast<size_t>(next)]);
        if (rn < 1 || rn > static_cast<std::int64_t>(area.recCount64())) return false;
        if (!area.gotoRec64(static_cast<std::uint64_t>(rn))) return false;
        return area.readCurrent();
    }

    case xindex::fmt::IndexFormat::INX: {
        std::vector<uint32_t> recnos;
        if (!order_nav_detail::load_inx_recnos(path, area.recCount(), recnos) || recnos.empty()) {
            if (!area.skip(delta)) return false;
            return area.readCurrent();
        }

        const bool asc = orderstate::isAscending(area);
        const int delta_eff = asc ? delta : -delta;

        const int32_t cur = area.recno();
        if (cur < 1 || cur > area.recCount()) return false;

        int32_t pos = -1;
        for (int32_t i = 0; i < static_cast<int32_t>(recnos.size()); ++i) {
            if (recnos[static_cast<size_t>(i)] == static_cast<uint32_t>(cur)) {
                pos = i;
                break;
            }
        }
        if (pos < 0) return false;

        // Partial-to-boundary (matches xBase SKIP-to-EOF).
        int32_t next = pos + delta_eff;
        const int32_t last = static_cast<int32_t>(recnos.size()) - 1;
        if (next < 0) next = 0;
        if (next > last) next = last;
        if (next == pos) return false; // already at the boundary; no move

        const int32_t rn = static_cast<int32_t>(recnos[static_cast<size_t>(next)]);
        if (rn < 1 || rn > area.recCount()) return false;
        if (!area.gotoRec(rn)) return false;
        return area.readCurrent();
    }

    case xindex::fmt::IndexFormat::SIX:
        // SIX is registered as a future/student index format.
        // Do not silently fall back to physical order while an unsupported order is active.
        return false;

    case xindex::fmt::IndexFormat::SCX:
        // SNX stub: this project currently names the second student/custom slot SCX
        // in IndexFormat. Treat it as the SNX placeholder until the enum is renamed
        // or an explicit SNX value is added in xindex/index_format_detect.hpp.
        return false;

    case xindex::fmt::IndexFormat::Unknown:
    default:
        if (!area.skip(delta)) return false;
        return area.readCurrent();
    }
}

static inline void order_nav_invalidate(xbase::DbArea& area) {
    if (!area.isOpen()) return;
    if (!orderstate::hasOrder(area)) return;

    const std::string path = orderstate::orderName(area);
    const auto fmt = order_nav_detail::detect_fmt(path);

    if (fmt == xindex::fmt::IndexFormat::INX) {
        order_nav_detail::cache_invalidate_path(order_nav_detail::fs::path(path));
    }

    if (fmt == xindex::fmt::IndexFormat::CNX ||
        fmt == xindex::fmt::IndexFormat::CDX) {
        order_nav_detail::cnx_cache_invalidate();
    }
}

static inline bool order_get_recnos(xbase::DbArea&,
                                   std::shared_ptr<std::vector<uint32_t>>&,
                                   std::shared_ptr<std::vector<int32_t>>&,
                                   int32_t&) {
    return false;
}