// ---- TVision uses ----
#define Uses_TRect
#define Uses_TMenuBar
#define Uses_TMenu
#define Uses_TSubMenu
#define Uses_TMenuItem
#define Uses_TKeys

#if DOTTALK_TV_AVAILABLE
#include <tvision/tv.h>
#endif

#include "tv/foxtalk_menu.hpp"
#include "tv/foxtalk_ids.hpp"
#include "tv/foxtalk_pro_menu_ids.hpp"
#include "tv/foxtalk_util.hpp"

namespace foxtalk {

TMenuBar* buildMenuBar(TRect bounds)
{
    bounds.b.y = S(bounds.a.y + 1);

    TMenu* root = new TMenu(
        *new TSubMenu("~S~ys", kbAltS)
            + *new TMenuItem("~A~bout DotTalk++ / TurboTalk...", cmFtSysAbout, kbNoKey, hcNoContext, "ABOUT")
            + *new TMenuItem("~V~ersion / Build Info", cmFtSysVersion, kbNoKey, hcNoContext, "VERSION")
            + *new TMenuItem("Runtime ~S~tatus", cmFtSysStatus, kbNoKey, hcNoContext, "STATUS")
            + *new TMenuItem("~P~aths / Environment", cmFtSysPaths, kbNoKey, hcNoContext, "SET PATH")
            + (TMenuItem&) (*new TSubMenu("~E~nvironment Scripts", kbNoKey)
                + *new TMenuItem("DotScript ~x~32", cmFtSysDotScriptX32, kbNoKey, hcNoContext, "DOTSCRIPT x32")
                + *new TMenuItem("DotScript x~6~4", cmFtSysDotScriptX64, kbNoKey, hcNoContext, "DOTSCRIPT x64")
                + *new TMenuItem("DotScript ~S~andbox", cmFtSysDotScriptSandbox, kbNoKey, hcNoContext, "DOTSCRIPT sandbox")
                + newLine()
                + *new TMenuItem("Run ~i~nit.ini", cmFtSysDotScriptInit, kbNoKey, hcNoContext, "DOTSCRIPT init.ini")
                + *new TMenuItem("Run s~h~utdown.ini", cmFtSysDotScriptShutdown, kbNoKey, hcNoContext, "DOTSCRIPT shutdown.ini")
                + *new TMenuItem("Show ~d~ottalkpp.ini", cmFtSysShowDottalkIni, kbNoKey, hcNoContext, "SHOWINI")
                + newLine()
                + *new TMenuItem("Edit ~d~ottalkpp.ini", cmFtSysEditDottalkIni, kbNoKey, hcNoContext, "TED dottalkpp.ini")
                + *new TMenuItem("Edit ~i~nit.ini", cmFtSysEditInitIni, kbNoKey, hcNoContext, "TED init.ini")
                + *new TMenuItem("Edit s~h~utdown.ini", cmFtSysEditShutdownIni, kbNoKey, hcNoContext, "TED shutdown.ini")
                + *new TMenuItem("Edit Dot~S~cript...", cmFtSysEditDotScript, kbNoKey, hcNoContext, "TED")
                + *new TMenuItem("New ~S~cratch Text", cmFtSysEditScratch, kbNoKey, hcNoContext, "TED"))
            + newLine()
            + *new TMenuItem("Color ~D~efault", cmFtSysColorDefault, kbNoKey, hcNoContext, "COLOR DEFAULT")
            + *new TMenuItem("Color ~G~reen", cmFtSysColorGreen, kbNoKey, hcNoContext, "COLOR GREEN")
            + *new TMenuItem("Color ~A~mber", cmFtSysColorAmber, kbNoKey, hcNoContext, "COLOR AMBER")
            + newLine()
            + *new TMenuItem("~S~hell Escape...", cmFtSysShell, kbNoKey, hcNoContext, "!")
            + *new TMenuItem("E~x~it TurboTalk", cmTalkExit, kbAltX, hcNoContext, "Alt-X")

      + *new TSubMenu("~F~ile", kbAltF)
            + *new TMenuItem("~O~pen Table...", cmFtFileUse, kbNoKey, hcNoContext, "USE")
            + *new TMenuItem("~C~lose Current Table", cmFtFileClose, kbNoKey, hcNoContext, "CLOSE")
            + *new TMenuItem("Close ~A~ll Tables", cmFtFileCloseAll, kbNoKey, hcNoContext, "WORKSPACE CLOSE")
            + *new TMenuItem("~S~elect Work Area...", cmFtFileSelect, kbNoKey, hcNoContext, "SELECT")
            + *new TMenuItem("~D~irectory...", cmFtFileDir, kbNoKey, hcNoContext, "DIR")
            + newLine()
            + *new TMenuItem("~I~mport CSV...", cmFtFileImport, kbNoKey, hcNoContext, "IMPORT")
            + *new TMenuItem("~E~xport CSV...", cmFtFileExport, kbNoKey, hcNoContext, "EXPORT")
            + *new TMenuItem("Run Dot~S~cript...", cmFtFileDotScript, kbNoKey, hcNoContext, "DOTSCRIPT")
            + *new TMenuItem("~E~dit Text / DotScript...", cmFtSysEditDotScript, kbNoKey, hcNoContext, "TED")
            + newLine()
            + *new TMenuItem("Save ~L~ayout", cmWinSave, kbNoKey, hcNoContext, "WIN SAVE")
            + *new TMenuItem("~R~estore Layout", cmWinRestore, kbNoKey, hcNoContext, "WIN RESTORE")
            + *new TMenuItem("~D~efault Window Layout", cmWinDefaults, kbNoKey, hcNoContext, "WIN DEFAULTS")

      + *new TSubMenu("Wor~k~", kbAltK)
            + *new TMenuItem("Workspace ~S~ummary", cmFtWorkSummary, kbNoKey, hcNoContext, "WORKSPACE")
            + *new TMenuItem("Open ~D~BF Workspace", cmFtWorkOpenDbf, kbNoKey, hcNoContext, "WORKSPACE OPEN DBF")
            + *new TMenuItem("Open Workspace From ~F~older...", cmFtWorkOpenDir, kbNoKey, hcNoContext, "WORKSPACE OPEN")
            + *new TMenuItem("~S~ave Workspace...", cmFtWorkSave, kbNoKey, hcNoContext, "WORKSPACE SAVE")
            + *new TMenuItem("~L~oad Workspace...", cmFtWorkLoad, kbNoKey, hcNoContext, "WORKSPACE LOAD")
            + *new TMenuItem("~C~lose Workspace", cmFtWorkClose, kbNoKey, hcNoContext, "WORKSPACE CLOSE")
            + newLine()
            + *new TMenuItem("Current ~A~rea", cmFtWorkArea, kbNoKey, hcNoContext, "AREA")
            + *new TMenuItem("Current ~D~bArea Diagnostics", cmFtWorkDbarea, kbNoKey, hcNoContext, "DBAREA")
            + *new TMenuItem("~A~ll DbAreas", cmFtWorkDbareas, kbNoKey, hcNoContext, "DBAREAS")
            + *new TMenuItem("Workspace ~R~eport", cmFtWorkReport, kbNoKey, hcNoContext, "WSREPORT")
            + *new TMenuItem("Re~f~resh Workspace View", cmFtWorkRefresh, kbNoKey, hcNoContext, "REFRESH")

      + *new TSubMenu("~E~rz", kbAltE)
            + *new TMenuItem("Restore ~M~CC Demo", cmFtErsatzMcc, kbNoKey, hcNoContext, "ERSATZ MCC")
            + *new TMenuItem("Restore Ersatz...", cmFtErsatzPrompt, kbNoKey, hcNoContext, "ERSATZ")
            + newLine()
            + *new TMenuItem("Show ~W~orkspace", cmFtErsatzWorkspace, kbNoKey, hcNoContext, "WORKSPACE")
            + *new TMenuItem("Show ~R~elations", cmFtErsatzRelAll, kbNoKey, hcNoContext, "REL LIST ALL")
            + *new TMenuItem("Open ~R~ecord View", cmFtErsatzRecord, kbNoKey, hcNoContext, "RECORDVIEW")

      + *new TSubMenu("~T~able", kbAltT)
            + *new TMenuItem("~S~tructure", cmFtTableStruct, kbNoKey, hcNoContext, "STRUCT")
            + *new TMenuItem("~F~ields", cmFtTableFields, kbNoKey, hcNoContext, "FIELDS")
            + *new TMenuItem("Table ~S~tatus", cmFtTableStatus, kbNoKey, hcNoContext, "STATUS")
            + *new TMenuItem("~M~etadata", cmFtTableMeta, kbNoKey, hcNoContext, "TABLEMETA")
            + *new TMenuItem("~V~alidate", cmFtTableValidate, kbNoKey, hcNoContext, "VALIDATE")
            + *new TMenuItem("Schema / ~D~DL", cmFtTableDDL, kbNoKey, hcNoContext, "DDL")
            + *new TMenuItem("~S~how Internal State", cmFtTableShow, kbNoKey, hcNoContext, "SHOW")
            + newLine()
            + *new TMenuItem("Buffering ~O~n", cmFtTableBufferOn, kbNoKey, hcNoContext, "TABLE ON")
            + *new TMenuItem("Buffering O~f~f", cmFtTableBufferOff, kbNoKey, hcNoContext, "TABLE OFF")
            + *new TMenuItem("Show ~S~tale Fields", cmFtTableStale, kbNoKey, hcNoContext, "TABLE STALE")
            + *new TMenuItem("Apply / ~F~resh", cmFtTableFresh, kbNoKey, hcNoContext, "TABLE FRESH")
            + newLine()
            + *new TMenuItem("~C~ommit Changes", cmFtTableCommit, kbNoKey, hcNoContext, "COMMIT")
            + *new TMenuItem("~R~ollback Changes (manual)", cmFtTableRollback, kbNoKey, hcNoContext, "ROLLBACK")

      + *new TSubMenu("Recor~d~", kbAltD)
            + *new TMenuItem("~R~ecord View", cmFtRecView, kbF3, hcNoContext, "F3")
            + *new TMenuItem("~D~isplay Current", cmFtRecDisplay, kbNoKey, hcNoContext, "DISPLAY")
            + *new TMenuItem("Current Record ~C~ontext", cmFtRecContext, kbNoKey, hcNoContext, "RECORD")
            + newLine()
            + *new TMenuItem("~G~o To Record...", cmFtRecGoto, kbNoKey, hcNoContext, "GOTO")
            + *new TMenuItem("~T~op", cmFtRecTop, kbNoKey, hcNoContext, "TOP")
            + *new TMenuItem("~B~ottom", cmFtRecBottom, kbNoKey, hcNoContext, "BOTTOM")
            + *new TMenuItem("Skip ~F~orward", cmFtRecSkipForward, kbNoKey, hcNoContext, "SKIP 1")
            + *new TMenuItem("Skip Bac~k~", cmFtRecSkipBack, kbNoKey, hcNoContext, "SKIP -1")
            + newLine()
            + *new TMenuItem("~A~ppend", cmFtRecAppend, kbNoKey, hcNoContext, "APPEND")
            + *new TMenuItem("Append ~B~lank", cmFtRecAppendBlank, kbNoKey, hcNoContext, "APPEND_BLANK")
            + *new TMenuItem("~E~dit", cmFtRecEdit, kbNoKey, hcNoContext, "EDIT")
            + *new TMenuItem("~R~eplace Field...", cmFtRecReplace, kbNoKey, hcNoContext, "REPLACE")
            + *new TMenuItem("~D~elete", cmFtRecDelete, kbNoKey, hcNoContext, "DELETE")
            + *new TMenuItem("Re~c~all", cmFtRecRecall, kbNoKey, hcNoContext, "RECALL")
            + *new TMenuItem("~P~ack", cmFtRecPack, kbNoKey, hcNoContext, "PACK")
            + *new TMenuItem("~Z~ap All Records...", cmFtRecZapSafe, kbNoKey, hcNoContext, "ZAP")
            + newLine()
            + *new TMenuItem("~L~ock Record", cmFtRecLock, kbNoKey, hcNoContext, "LOCK")
            + *new TMenuItem("~U~nlock", cmFtRecUnlock, kbNoKey, hcNoContext, "UNLOCK")

      + *new TSubMenu("~I~ndex", kbAltI)
            + *new TMenuItem("Set ~I~ndex Container...", cmFtIdxSetIndex, kbNoKey, hcNoContext, "SET INDEX TO")
            + *new TMenuItem("Set ~O~rder / Tag...", cmFtIdxSetOrder, kbNoKey, hcNoContext, "SET ORDER TO")
            + *new TMenuItem("~P~hysical Order", cmFtIdxPhysical, kbNoKey, hcNoContext, "SET ORDER TO 0")
            + newLine()
            + *new TMenuItem("~S~eek Key...", cmFtIdxSeek, kbNoKey, hcNoContext, "SEEK")
            + *new TMenuItem("~F~ind Key...", cmFtIdxFind, kbNoKey, hcNoContext, "FIND")
            + *new TMenuItem("Index~S~eek...", cmFtIdxIndexSeek, kbNoKey, hcNoContext, "INDEXSEEK")
            + newLine()
            + *new TMenuItem("~A~scending", cmFtIdxAscend, kbNoKey, hcNoContext, "ASCEND")
            + *new TMenuItem("~D~escending", cmFtIdxDescend, kbNoKey, hcNoContext, "DESCEND")
            + *new TMenuItem("~R~eindex", cmFtIdxReindex, kbNoKey, hcNoContext, "REINDEX")
            + *new TMenuItem("~B~uild LMDB-CDX", cmFtIdxBuildLmdb, kbNoKey, hcNoContext, "BUILDLMDB")
            + newLine()
            + *new TMenuItem("~C~NX Container", cmFtIdxCnx, kbNoKey, hcNoContext, "CNX")
            + *new TMenuItem("CD~X~ Diagnostics", cmFtIdxCdx, kbNoKey, hcNoContext, "CDX")
            + *new TMenuItem("~L~MDB Diagnostics", cmFtIdxLmdb, kbNoKey, hcNoContext, "LMDB")

      + *new TSubMenu("~L~ists", kbAltL)
            + *new TMenuItem("~L~ist Records", cmFtListList, kbNoKey, hcNoContext, "LIST")
            + *new TMenuItem("List First ~1~0", cmFtListList10, kbNoKey, hcNoContext, "LIST 10")
            + *new TMenuItem("~S~martList", cmFtListSmart, kbNoKey, hcNoContext, "SMARTLIST")
            + *new TMenuItem("SmartList ~F~OR...", cmFtListSmartFilter, kbNoKey, hcNoContext, "SMARTLIST FOR")
            + *new TMenuItem("~D~isplay Current", cmFtListDisplay, kbNoKey, hcNoContext, "DISPLAY")
            + newLine()
            + *new TMenuItem("~C~ount", cmFtListCount, kbNoKey, hcNoContext, "COUNT")
            + *new TMenuItem("S~u~m", cmFtListSum, kbNoKey, hcNoContext, "SUM")
            + *new TMenuItem("~A~verage", cmFtListAverage, kbNoKey, hcNoContext, "AVERAGE")
            + newLine()
            + *new TMenuItem("~W~HERE / SQL-like Filter...", cmFtListWhere, kbNoKey, hcNoContext, "WHERE")
            + *new TMenuItem("Set ~F~ilter...", cmFtListSetFilter, kbNoKey, hcNoContext, "SET FILTER TO")
            + *new TMenuItem("~C~lear Filter", cmFtListClearFilter, kbNoKey, hcNoContext, "SET FILTER TO")
            + newLine()
            + *new TMenuItem("~P~redicate Help", cmFtListPredHelp, kbNoKey, hcNoContext, "PREDHELP")
            + *new TMenuItem("Predicate ~C~atalog", cmFtListPredicates, kbNoKey, hcNoContext, "PREDICATES")

      + *new TSubMenu("~B~rowse", kbAltB)
            + *new TMenuItem("~B~rowse Current Table", cmFtBrowseCurrent, kbNoKey, hcNoContext, "BROWSE")
            + *new TMenuItem("~S~imple Browser", cmFtBrowseSimple, kbNoKey, hcNoContext, "SIMPLEBROWSER")
            + *new TMenuItem("S~m~art Browser", cmFtBrowseSmart, kbNoKey, hcNoContext, "SMARTBROWSER")
            + *new TMenuItem("~T~ext Browser (outer CLI)", cmFtBrowseText, kbNoKey, hcNoContext, "BROWSETUI")
            + *new TMenuItem("Turbo ~V~ision Browser (outer CLI)", cmFtBrowseTv, kbNoKey, hcNoContext, "BROWSETV")
            + *new TMenuItem("~D~eveloper Browser", cmFtBrowseDev, kbNoKey, hcNoContext, "BROWSER")
            + newLine()
            + *new TMenuItem("~R~ecord View", cmFtBrowseRecord, kbNoKey, hcNoContext, "RECORDVIEW")
            + *new TMenuItem("Related ~C~hildren...", cmFtBrowseChildren, kbNoKey, hcNoContext, "SIMPLEBROWSER SHOW CHILDREN")
            + *new TMenuItem("Browse ~F~OR...", cmFtBrowseFor, kbNoKey, hcNoContext, "SIMPLEBROWSER FOR")
            + *new TMenuItem("Browse ~O~RDER...", cmFtBrowseOrder, kbNoKey, hcNoContext, "SIMPLEBROWSER ORDER")

      + *new TSubMenu("~R~el", kbAltR)
            + *new TMenuItem("Set ~R~elation...", cmFtRelSet, kbNoKey, hcNoContext, "SET RELATION TO")
            + *new TMenuItem("Set Relation ~A~dditive...", cmFtRelSetAdd, kbNoKey, hcNoContext, "SET RELATION ADDITIVE TO")
            + *new TMenuItem("Relation ~O~ff Into...", cmFtRelOffInto, kbNoKey, hcNoContext, "SET RELATION OFF INTO")
            + *new TMenuItem("Clear Current Relations", cmFtRelOffAll, kbNoKey, hcNoContext, "SET RELATION OFF ALL")
            + newLine()
            + *new TMenuItem("Relation ~L~ist", cmFtRelList, kbNoKey, hcNoContext, "REL LIST")
            + *new TMenuItem("Relation List ~A~ll", cmFtRelListAll, kbNoKey, hcNoContext, "REL LIST ALL")
            + *new TMenuItem("Relation Re~f~resh", cmFtRelRefresh, kbNoKey, hcNoContext, "REL REFRESH")
            + newLine()
            + *new TMenuItem("~A~dd Native Relation...", cmFtRelAdd, kbNoKey, hcNoContext, "REL ADD")
            + *new TMenuItem("~C~lear Native Relation...", cmFtRelClear, kbNoKey, hcNoContext, "REL CLEAR")
            + *new TMenuItem("~S~ave Relations...", cmFtRelSave, kbNoKey, hcNoContext, "REL SAVE")
            + *new TMenuItem("~L~oad Relations...", cmFtRelLoad, kbNoKey, hcNoContext, "REL LOAD")
            + *new TMenuItem("~E~numerate Relation Path...", cmFtRelEnum, kbNoKey, hcNoContext, "REL ENUM")

      + *new TSubMenu("T~u~ple", kbAltU)
            + *new TMenuItem("Tuple ~A~ll Fields", cmFtTupleAll, kbNoKey, hcNoContext, "TUPLE *")
            + *new TMenuItem("Tuple ~F~ields...", cmFtTupleFields, kbNoKey, hcNoContext, "TUPLE")
            + *new TMenuItem("Tuple From ~A~rea...", cmFtTupleArea, kbNoKey, hcNoContext, "TUPLE #n.*")
            + *new TMenuItem("~M~ixed-Area Tuple...", cmFtTupleMixed, kbNoKey, hcNoContext, "TUPLE #9.*,#11.LNAME")
            + newLine()
            + *new TMenuItem("~T~upTalk", cmFtTupleTuptalk, kbNoKey, hcNoContext, "TUPTALK")
            + *new TMenuItem("Tuple ~E~xport", cmFtTupleExport, kbNoKey, hcNoContext, "TUPEXPORT")
            + *new TMenuItem("Tuple ~V~alidate", cmFtTupleValidate, kbNoKey, hcNoContext, "TUPVALIDATE")
            + *new TMenuItem("Relation Tuple E~n~um...", cmFtTupleRelEnum, kbNoKey, hcNoContext, "REL ENUM ... TUPLE")

      + *new TSubMenu("Fu~n~cs", kbAltN)
            + *new TMenuItem("~C~alculator / CALC...", cmFtFuncCalc, kbNoKey, hcNoContext, "CALC")
            + *new TMenuItem("~E~valuate Expression...", cmFtFuncEval, kbNoKey, hcNoContext, "EVAL")
            + *new TMenuItem("Expression Function ~C~atalog", cmFtFuncCatalog, kbNoKey, hcNoContext, "EXPFUNCS")
            + newLine()
            + *new TMenuItem("~P~redicate Help", cmFtFuncPredHelp, kbNoKey, hcNoContext, "PREDHELP")
            + *new TMenuItem("Predicate ~C~atalog", cmFtFuncPredicates, kbNoKey, hcNoContext, "PREDICATES")
            + newLine()
            + *new TMenuItem("UPPER() Example", cmFtFuncUpper, kbNoKey, hcNoContext, "CALC UPPER()")
            + *new TMenuItem("DATE() Example", cmFtFuncDate, kbNoKey, hcNoContext, "CALC DATE()")
            + *new TMenuItem("~N~umeric Functions Help", cmFtFuncNumericHelp, kbNoKey, hcNoContext, "HELP ABS")
            + *new TMenuItem("~S~tring Functions Help", cmFtFuncStringHelp, kbNoKey, hcNoContext, "HELP UPPER")

      + *new TSubMenu("~C~md", kbAltC)
            + *new TMenuItem("~H~elp", cmFtCmdHelp, kbNoKey, hcNoContext, "HELP")
            + *new TMenuItem("~F~ox Help", cmFtCmdFoxHelp, kbNoKey, hcNoContext, "FOXHELP")
            + *new TMenuItem("Command ~C~atalog", cmFtCmdCatalog, kbNoKey, hcNoContext, "CMDHELP")
            + *new TMenuItem("~B~uild Command Catalog", cmFtCmdBuildCatalog, kbNoKey, hcNoContext, "CMDHELP BUILD")
            + *new TMenuItem("~V~alidate Command Catalog", cmFtCmdValidateCatalog, kbNoKey, hcNoContext, "CMDHELPCHK")
            + *new TMenuItem("~A~rgument Parser Check", cmFtCmdArgCheck, kbNoKey, hcNoContext, "CMDARGCHK")
            + *new TMenuItem("CommandsHelp", cmFtCmdCommandsHelp, kbNoKey, hcNoContext, "COMMANDSHELP")
            + newLine()
            + *new TMenuItem("Run ~D~otScript...", cmFtCmdDotScript, kbNoKey, hcNoContext, "DOTSCRIPT")
            + *new TMenuItem("~T~est Harness", cmFtCmdTest, kbNoKey, hcNoContext, "TEST")
            + *new TMenuItem("~S~how State", cmFtCmdShow, kbNoKey, hcNoContext, "SHOW")
            + *new TMenuItem("D~u~mp State", cmFtCmdDump, kbNoKey, hcNoContext, "DUMP")
            + *new TMenuItem("Set ~V~ariable...", cmFtCmdSetVar, kbNoKey, hcNoContext, "SET VAR")
            + *new TMenuItem("Force Set Variable...", cmFtCmdSetVarBang, kbNoKey, hcNoContext, "SET VAR!")
            + newLine()
            + *new TMenuItem("SQL ~V~ersion", cmFtCmdSqlVersion, kbNoKey, hcNoContext, "SQLVER")
            + *new TMenuItem("~S~QLite Status", cmFtCmdSqlite, kbNoKey, hcNoContext, "SQLITE")
            + *new TMenuItem("SQL ~E~xecute...", cmFtCmdSqlExec, kbNoKey, hcNoContext, "SQL")
            + *new TMenuItem("SQL Se~l~ect...", cmFtCmdSqlSelect, kbNoKey, hcNoContext, "SQLSEL")

      + *new TSubMenu("~W~indow", kbAltW)
            + *new TMenuItem("~O~utput", cmShowOutput, kbF2, hcNoContext, "F2")
            + *new TMenuItem("~C~ommand Bar", cmFocusCmd, kbCtrlQ, hcNoContext, "Ctrl-Q")
            + *new TMenuItem("~W~orkspace", cmWorkspace, kbF4, hcNoContext, "F4")
            + *new TMenuItem("~R~ecord View", cmFtRecView, kbF3, hcNoContext, "F3")
            + newLine()
            + *new TMenuItem("~Z~oom Command", cmZoomCmd, kbAltZ, hcNoContext, "Alt-Z")
            + *new TMenuItem("~R~estore Command", cmResetCmdWin, kbCtrlF5, hcNoContext, "Ctrl-F5")
            + *new TMenuItem("Z~o~om Output", cmZoomOut, kbAltO, hcNoContext, "Alt-O")
            + *new TMenuItem("R~e~store Output", cmResetOutWin, kbCtrlF6, hcNoContext, "Ctrl-F6")
            + *new TMenuItem("C~l~ear Output", cmFtWinClearOutput, kbNoKey, hcNoContext, "CLEAR OUTPUT")
            + newLine()
            + *new TMenuItem("Save ~L~ayout", cmWinSave, kbNoKey, hcNoContext, "WIN SAVE")
            + *new TMenuItem("~R~estore Layout", cmWinRestore, kbNoKey, hcNoContext, "WIN RESTORE")
            + *new TMenuItem("~D~efault Layout", cmWinDefaults, kbNoKey, hcNoContext, "WIN DEFAULTS")

      + *new TSubMenu("~H~elp", kbAltH)
            + *new TMenuItem("~H~elp", cmFtHelpMain, kbNoKey, hcNoContext, "HELP")
            + *new TMenuItem("Command Help...", cmFtHelpCommand, kbNoKey, hcNoContext, "HELP")
            + *new TMenuItem("~F~oxPro Compatibility Help", cmFtHelpFox, kbNoKey, hcNoContext, "FOXHELP")
            + *new TMenuItem("~P~redicate Help", cmFtHelpPred, kbNoKey, hcNoContext, "PREDHELP")
            + newLine()
            + *new TMenuItem("~W~orkspace Help", cmFtHelpWorkspace, kbNoKey, hcNoContext, "HELP WORKSPACE")
            + *new TMenuItem("~R~elations Help", cmFtHelpRelations, kbNoKey, hcNoContext, "HELP REL")
            + *new TMenuItem("~T~uple Help", cmFtHelpTuple, kbNoKey, hcNoContext, "HELP TUPLE")
            + *new TMenuItem("~B~rowser Help", cmFtHelpBrowser, kbNoKey, hcNoContext, "HELP SIMPLEBROWSER")
            + newLine()
            + *new TMenuItem("~K~eys Cheat Sheet", cmFtHelpKeys, kbNoKey, hcNoContext, "KEYS")
            + *new TMenuItem("~A~bout TurboTalk...", cmFtHelpAbout, kbNoKey, hcNoContext, "ABOUT")
    );

    return new TMenuBar(bounds, root);
}

} // namespace foxtalk
