#!/usr/bin/env python3
"""Generate GUI message adapters from the shared CSV seed."""

from __future__ import annotations

import argparse
import csv
import pathlib
import re
import sys


REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
SOURCE = REPO_ROOT / "dottalkpp" / "data" / "messaging" / "gui_messages.csv"
CPP_OUT = REPO_ROOT / "include" / "gui" / "core" / "generated_gui_messages.hpp"
PY_OUT = REPO_ROOT / "tools" / "gui_preview" / "generated_gui_text.py"
LOCALES = ("en-US", "es", "fr", "de", "it")


def cpp_escape(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def py_repr(value: str) -> str:
    return repr(value)


def load_rows() -> list[dict[str, str]]:
    with SOURCE.open("r", encoding="utf-8", newline="") as handle:
        rows = list(csv.DictReader(handle))
    required = {"enum", "key", *LOCALES}
    if not rows:
        raise ValueError(f"{SOURCE} has no rows")
    missing = required - set(rows[0])
    if missing:
        raise ValueError(f"{SOURCE} missing columns: {sorted(missing)}")
    seen_enums: set[str] = set()
    seen_keys: set[str] = set()
    for index, row in enumerate(rows, start=2):
        enum = row["enum"].strip()
        key = row["key"].strip()
        if not enum or not re.fullmatch(r"[A-Za-z][A-Za-z0-9]*", enum):
            raise ValueError(f"{SOURCE}:{index}: invalid enum {enum!r}")
        if not key or not key.startswith("gui."):
            raise ValueError(f"{SOURCE}:{index}: invalid key {key!r}")
        if enum in seen_enums:
            raise ValueError(f"{SOURCE}:{index}: duplicate enum {enum!r}")
        if key in seen_keys:
            raise ValueError(f"{SOURCE}:{index}: duplicate key {key!r}")
        seen_enums.add(enum)
        seen_keys.add(key)
        for locale in LOCALES:
            if not row[locale]:
                row[locale] = row["en-US"]
    return rows


def render_cpp(rows: list[dict[str, str]]) -> str:
    lines = [
        "// Generated by tools/gui/generate_gui_messages.py. Do not edit by hand.",
        "#pragma once",
        "",
        "#include \"gui/core/localization.hpp\"",
        "",
        "namespace dottalk::gui::generated {",
        "",
        "struct GuiMessageSeed {",
        "    GuiTextId id;",
        "    const char* key;",
        "    const char* en_us;",
        "    const char* es;",
        "    const char* fr;",
        "    const char* de;",
        "    const char* it;",
        "};",
        "",
        "inline constexpr const char* k_gui_message_locales[] = {",
    ]
    for locale in LOCALES:
        lines.append(f"    \"{cpp_escape(locale)}\",")
    lines.extend([
        "};",
        "",
        "inline constexpr GuiMessageSeed k_gui_message_seed[] = {",
    ])
    for row in rows:
        lines.append(
            "    {GuiTextId::%s, \"%s\", \"%s\", \"%s\", \"%s\", \"%s\", \"%s\"},"
            % (
                row["enum"],
                cpp_escape(row["key"]),
                cpp_escape(row["en-US"]),
                cpp_escape(row["es"]),
                cpp_escape(row["fr"]),
                cpp_escape(row["de"]),
                cpp_escape(row["it"]),
            )
        )
    lines.extend([
        "};",
        "",
        "} // namespace dottalk::gui::generated",
        "",
    ])
    return "\n".join(lines)


def render_py(rows: list[dict[str, str]]) -> str:
    lines = [
        '"""Generated GUI text seed. Do not edit by hand."""',
        "",
        "from __future__ import annotations",
        "",
        f"SUPPORTED_LOCALES = {LOCALES!r}",
        "",
        "TEXT: dict[str, dict[str, str]] = {",
    ]
    for row in rows:
        lines.append(f"    {py_repr(row['key'])}: {{")
        for locale in LOCALES:
            lines.append(f"        {py_repr(locale)}: {py_repr(row[locale])},")
        lines.append("    },")
    lines.extend([
        "}",
        "",
    ])
    return "\n".join(lines)


def write_if_changed(path: pathlib.Path, text: str) -> bool:
    old = path.read_text(encoding="utf-8") if path.exists() else None
    if old == text:
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8", newline="\n")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail if generated files are stale")
    args = parser.parse_args()

    rows = load_rows()
    outputs = {
        CPP_OUT: render_cpp(rows),
        PY_OUT: render_py(rows),
    }

    stale: list[pathlib.Path] = []
    for path, text in outputs.items():
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(path)
        else:
            write_if_changed(path, text)

    if stale:
        for path in stale:
            print(f"stale: {path}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
