#!/usr/bin/env python3
"""Generate the Cascade ERP .dtgraph and the index-build DotScript.

Reads the generated sidecar metadata under systems/cascade_erp/meta/
(*.ddl.json, *.indexes.json, *.schema.copy.json) and emits:

  1. systems/cascade_erp/schema/CASCADE_ERP.dtgraph
       Declarative x64base schema: per table -> fields, index tags with
       order and uniqueness, and foreign-key relations. dts-like syntax,
       ASCII. Comment style (owner rule 2026-08-10): `* ` opens a full-line
       comment; `&&` only trails content on the same line.
       GENERATED -- never hand-edit; the sidecar
       JSONs remain the measured authority (AIF-105 rule 12) and this file
       records their aggregate SHA-256 so drift is detectable.

  2. systems/cascade_erp/scripts/cascade_erp_build_indexes.dts
       Executable DotScript that builds the physical indexes the sidecars
       declare as metadata_only: per table USE / CDX CREATE / CDX ADDTAG.

Honesty rules carried from the AIF-105 lane charter:
  - The PRIMARY KEY column is parsed from the preserved CREATE TABLE SQL in
    each schema.copy.json (declared DDL, not value inference).
  - `CDX ADDTAG <name>` takes a single field name (src/cli/cmd_cdx.cpp), so
    composite indexes are declared in the .dtgraph with their full column
    order but built as a tag on the LEADING column, explicitly labeled
    `partial(engine: single-name ADDTAG)`. Unsupported is labeled, not hidden.
  - Relations are declared; sidecar semantics, not native DBF enforcement.

Stdlib only. Deterministic output (sorted tables, stable field order).
"""
from __future__ import annotations

import hashlib
import json
import re
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
SYSTEM_ROOT = REPO_ROOT / "dottalkpp" / "data" / "systems" / "cascade_erp"
META_DIR = SYSTEM_ROOT / "meta"
SCHEMA_OUT = SYSTEM_ROOT / "schema" / "CASCADE_ERP.dtgraph"
BUILD_OUT = SYSTEM_ROOT / "scripts" / "cascade_erp_build_indexes.dts"
GRAPH_OUT = SYSTEM_ROOT / "schema" / "CASCADE_ERP.graph.mmd"
VIEWER_OUT = SYSTEM_ROOT / "schema" / "CASCADE_ERP.graph.html"

PK_RE = re.compile(r"^\s*(\w+)\s+INTEGER\s+PRIMARY\s+KEY", re.IGNORECASE | re.MULTILINE)


def meta_digest() -> str:
    h = hashlib.sha256()
    for p in sorted(META_DIR.glob("*.json")):
        h.update(p.name.encode())
        h.update(p.read_bytes())
    return h.hexdigest()


def descriptor(ddl: dict, logical: str) -> str:
    """Map a logical column name to its stored DBF descriptor name."""
    for f in ddl.get("fields", []):
        if f.get("name", "").lower() == logical.lower():
            return f.get("descriptor_name", logical[:10].upper())
    return logical[:10].upper()


def load_table(base: str):
    ddl = json.loads((META_DIR / f"{base}.ddl.json").read_text())
    idx = json.loads((META_DIR / f"{base}.indexes.json").read_text())
    copy = json.loads((META_DIR / f"{base}.schema.copy.json").read_text())
    return ddl, idx, copy


def pk_column(copy: dict) -> str | None:
    sql = copy.get("x-cascade", {}).get("sqlite_sql", "")
    m = PK_RE.search(sql)
    return m.group(1) if m else None


def main() -> int:
    bases = sorted(p.name[: -len(".ddl.json")] for p in META_DIR.glob("*.ddl.json"))
    if not bases:
        print(f"ERROR: no *.ddl.json under {META_DIR}", file=sys.stderr)
        return 2

    digest = meta_digest()
    schema: list[str] = []
    build: list[str] = []

    schema += [
        "* CASCADE_ERP.dtgraph -- attributed relation graph: nodes are tables",
        "* (with fields and index tags), edges are FK relations. NOT a .dtschema:",
        "* that extension belongs to the engine WORKSPACE SAVE/LOAD snapshot",
        "* format (DTSHEMA), discovered 2026-08-10. Next consumer: the ERSATZ",
        "* relational browser (.erz sessions) -- edges plus child seek tags are",
        "* exactly what a relational browser needs to navigate.",
        "*",
        "* TWO HOUSE GRAPHS (owner doctrine 2026-08-10): x64base walks these same",
        "* edges two ways -- traditional SET RELATION (xBase navigation; REL",
        "* engine, workspace RELATION lines) and SQLSEL (declarative SQL, whose",
        "* row sets are confirmed against an in-process SQLite oracle -- see the",
        "* SQLSEL_SELECT_V1 regression). One graph, two walkers.",
        "*",
        "* TWO NAME PLANES (proven 2026-08-10, cascade_all load): x64 carries",
        "* LONG logical field names alongside 10-char DBF descriptors. The CDX",
        "* tag world eats DESCRIPTORS (CDX ADDTAG); the REL world eats LOGICAL",
        "* names (22 truncated names rejected, then 58/58 accepted as logical).",
        "* TAG lines below use descriptors; RELATION lines use logical names.",
        "* GENERATED by tools/cascade_erp/generate_dtschema.py -- do not hand-edit.",
        "* Authority: systems/cascade_erp/meta/*.json (AIF-105 sidecars).",
        f"* meta aggregate sha256: {digest}",
        "* Tag rule: PK parsed from preserved CREATE TABLE SQL; UNIQUE from",
        "* declared sqlite indexes; FK tags from declared relations. Composite",
        "* indexes keep full order here; the engine tag is on the leading",
        "* column and labeled partial (single-name ADDTAG).",
        "",
    ]

    build += [
        "* cascade_erp_build_indexes.dts -- build the physical CDX tags the",
        "* sidecars declare as metadata_only. GENERATED -- do not hand-edit.",
        "* Run AFTER cascade_erp.dts has set the environment, or standalone:",
        "SET TALK ON",
        "SET PATH DBF SYSTEMS/CASCADE_ERP/DBF",
        "SET PATH INDEXES SYSTEMS/CASCADE_ERP/INDEXES",
        "SET PATH LMDB SYSTEMS/CASCADE_ERP/LMDB",
        "ECHO CASCADE INDEX BUILD BEGIN",
        "",
    ]

    tables = views = tags = partials = rels = 0

    for base in bases:
        ddl, idx, copy = load_table(base)
        is_view = base.startswith("CASCADE_v_")
        (views_inc := is_view) and None
        if is_view:
            views += 1
        else:
            tables += 1

        schema.append(f"TABLE {base}")
        for f in ddl.get("fields", []):
            schema.append(
                "  FIELD {name:<11} {type} {length:>3} {dec}".format(
                    name=f.get("descriptor_name", "?"),
                    type=f.get("type", "?"),
                    length=f.get("length", 0),
                    dec=f.get("decimals", 0),
                )
            )

        table_tags: list[str] = []

        pk = None if is_view else pk_column(copy)
        if pk:
            d = descriptor(ddl, pk)
            schema.append(f"  TAG   {d:<11} PRIMARY UNIQUE")
            table_tags.append(d)
            tags += 1

        for i in idx.get("indexes", []):
            order = i.get("order", [])
            if not order:
                continue
            lead = descriptor(ddl, order[0])
            uniq = "UNIQUE" if i.get("unique") else ""
            if len(order) == 1:
                schema.append(f"  TAG   {lead:<11} {uniq}".rstrip())
            else:
                full = ",".join(descriptor(ddl, c) for c in order)
                schema.append(
                    f"  TAG   {lead:<11} {uniq} COMPOSITE({full}) "
                    "&& partial(engine: single-name ADDTAG)".rstrip()
                )
                partials += 1
            if lead not in table_tags:
                table_tags.append(lead)
                tags += 1

        for r in copy.get("relations", []):
            pairs = r.get("on", [])
            if not pairs:
                continue
            # RELATION lines live in the LOGICAL name plane (REL engine);
            # the FK seek TAG lives in the DESCRIPTOR plane (CDX engine).
            child_log = pairs[0]["child"].upper()
            parent_log = pairs[0]["parent"].upper()
            child_col = descriptor(ddl, pairs[0]["child"])
            parent = "CASCADE_" + r.get("parent_table", "?")
            schema.append(
                f"  RELATION {child_log} -> {parent}({parent_log}) "
                f"{r.get('cardinality','?')} enforce={r.get('enforce','?')}"
            )
            rels += 1
            if child_col not in table_tags:
                schema.append(f"  TAG   {child_col:<11} && FK seek tag")
                table_tags.append(child_col)
                tags += 1

        schema.append("")

        if table_tags:
            # No bare USE between tables: USE has no zero-arg close form
            # (proven by datarun 2026-08-10 -- it prints usage); the next
            # USE <table> closes/resets the area itself.
            build.append(f"USE {base}")
            build.append("CDX CREATE")
            for t in table_tags:
                build.append(f"CDX ADDTAG {t}")
            # The .cdx is the tag directory; physical order data lives in the
            # LMDB backend. Without this, SET INDEX reports "CDX container
            # found but LMDB env missing" (proven by datarun 2026-08-10; the
            # engine's own hint names this fix).
            build.append("BUILDLMDB")
            build.append("")

    build += ["ECHO CASCADE INDEX BUILD END", "DIR"]

    # ---- relation graph (generated FROM metadata; never schema authority) ----
    # One logical schema, two carriers: these edges are the FK constraints
    # declared in the sealed SQLite carrier, projected through the sidecars.
    # SQLite enforces them natively; x64base carries them as sidecar semantics
    # plus FK seek tags. If a rendered graph ever disagrees with ERP RELATIONS,
    # something upstream broke -- that diff is the parity check.
    edges: list[tuple[str, str, str]] = []
    for base in bases:
        if base.startswith("CASCADE_v_"):
            continue
        _, _, copy = load_table(base)
        child = base[len("CASCADE_"):]
        for r in copy.get("relations", []):
            pairs = r.get("on", [])
            if not pairs:
                continue
            edges.append((child, r.get("parent_table", "?"), pairs[0]["child"]))
    edges.sort()

    mmd = [
        "%% CASCADE_ERP.graph.mmd -- FK relation graph, GENERATED by",
        "%% tools/cascade_erp/generate_dtschema.py from systems/cascade_erp/meta/.",
        "%% Never an independent schema authority (AIF-105).",
        f"%% meta aggregate sha256: {digest}",
        f"%% {len(edges)} edges (child -->|fk column| parent)",
        "graph LR",
    ]
    for child, parent, col in edges:
        mmd.append(f"  {child} -->|{col}| {parent}")

    GRAPH_OUT.write_text("\n".join(mmd) + "\n", encoding="ascii")

    viewer = (
        "<!DOCTYPE html>\n<html><head><meta charset=\"ascii\">"
        "<title>Cascade ERP relation graph (generated)</title></head>\n"
        "<body style=\"background:#0b1220;color:#dbe7ff;font-family:sans-serif\">\n"
        "<p>Cascade ERP FK relation graph -- GENERATED from sidecar metadata; "
        "never schema authority. Source: CASCADE_ERP.graph.mmd (same dir). "
        "Requires internet for the Mermaid CDN; offline, paste the .mmd into "
        "any Mermaid renderer.</p>\n<pre class=\"mermaid\">\n"
        + "\n".join(mmd[5:])
        + "\n</pre>\n"
        "<script type=\"module\">import mermaid from "
        "\"https://cdn.jsdelivr.net/npm/mermaid@10/dist/mermaid.esm.min.mjs\";"
        "mermaid.initialize({startOnLoad:true,theme:\"dark\",maxEdges:2000});"
        "</script>\n</body></html>\n"
    )
    VIEWER_OUT.write_text(viewer, encoding="ascii")

    schema.insert(
        8,
        f"* census: {tables} tables, {views} view snapshots, {tags} tags "
        f"({partials} composite/partial), {rels} relations",
    )

    SCHEMA_OUT.parent.mkdir(parents=True, exist_ok=True)
    BUILD_OUT.parent.mkdir(parents=True, exist_ok=True)
    SCHEMA_OUT.write_text("\n".join(schema) + "\n", encoding="ascii")
    BUILD_OUT.write_text("\n".join(build) + "\n", encoding="ascii")
    print(f"wrote {SCHEMA_OUT.relative_to(REPO_ROOT)}")
    print(f"wrote {BUILD_OUT.relative_to(REPO_ROOT)}")
    print(f"wrote {GRAPH_OUT.relative_to(REPO_ROOT)} ({len(edges)} edges)")
    print(f"wrote {VIEWER_OUT.relative_to(REPO_ROOT)}")
    print(
        f"census: {tables} tables, {views} views, {tags} tags "
        f"({partials} partial), {rels} relations"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
