        // Phase 1 DOT identity promotion for classic database commands.
        // FOX compatibility entries remain in foxref.hpp.
        // Generated by patch_dotref_phase1_classic_db.py.
        {"AREA", "AREA", "Report the current DotTalk++ work-area state.", true},
        {"BOTTOM", "BOTTOM", "Move to the last record in the current table/order.", true},
        {"COUNT", "COUNT [FOR <expr>]", "Count records in the current table, optionally using a FOR expression.", true},
        {"DISPLAY", "DISPLAY [ALL] [FIELDS <list>] [FOR <expr>]", "Display records from the current table without changing the default DOT help namespace.", true},
        {"FIND", "FIND <text> [IN <field>]", "Find text or values using the active order when possible, with scan fallback when needed.", true},
        {"GOTO", "GOTO <recno>|TOP|BOTTOM", "Move the current work area to a specific record or boundary position.", true},
        {"LIST", "LIST [ALL] [FIELDS <list>] [FOR <expr>]", "List records from the current table using DotTalk++ command semantics.", true},
        {"LOCATE", "LOCATE FOR <expr> | LOCATE <field> <op> <value>", "Position on the first record matching a predicate or simple field comparison.", true},
        {"RECNO", "RECNO", "Report the current record number for the active work area.", true},
        {"SELECT", "SELECT <area-or-alias>", "Select the active DotTalk++ work area by number or logical name.", true},
        {"SET", "SET [<option> [<value>]]", "Show or change DotTalk++ runtime settings.", true},
        {"SKIP", "SKIP [<n>]", "Move relative to the current record in the active work area.", true},
        {"TOP", "TOP", "Move to the first record in the current table/order.", true},
        {"USE", "USE <table> [ALIAS <name>] [NOINDEX]", "Open a DBF table in the active DotTalk++ work area.", true},
